// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/service/v1/storage_config.proto

package v1

import (
	_ "backend-service/api/common/enum"
	_ "backend-service/api/common/pagination"
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 租户存储配置
type StorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置ID
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 配置名称
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 存储供应商
	Provider *string `protobuf:"bytes,3,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	// 用途标签
	Purpose *string `protobuf:"bytes,4,opt,name=purpose,proto3,oneof" json:"purpose,omitempty"`
	// 默认桶名
	Bucket *string `protobuf:"bytes,5,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	// 是否默认
	IsDefault *bool `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	// 供应商专属配置JSON
	ConfigJson *string `protobuf:"bytes,7,opt,name=config_json,json=configJson,proto3,oneof" json:"config_json,omitempty"`
	// 健康状态
	HealthStatus *string `protobuf:"bytes,8,opt,name=health_status,json=healthStatus,proto3,oneof" json:"health_status,omitempty"`
	// 创建时间
	CreatedAt *string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     *string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{0}
}

func (x *StorageConfig) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *StorageConfig) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *StorageConfig) GetPurpose() string {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return ""
}

func (x *StorageConfig) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *StorageConfig) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *StorageConfig) GetConfigJson() string {
	if x != nil && x.ConfigJson != nil {
		return *x.ConfigJson
	}
	return ""
}

func (x *StorageConfig) GetHealthStatus() string {
	if x != nil && x.HealthStatus != nil {
		return *x.HealthStatus
	}
	return ""
}

func (x *StorageConfig) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *StorageConfig) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type CreateStorageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Provider      *string                `protobuf:"bytes,2,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Purpose       *string                `protobuf:"bytes,3,opt,name=purpose,proto3,oneof" json:"purpose,omitempty"`
	Bucket        *string                `protobuf:"bytes,4,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	IsDefault     *bool                  `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	ConfigJson    *string                `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3,oneof" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStorageConfigRequest) Reset() {
	*x = CreateStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageConfigRequest) ProtoMessage() {}

func (x *CreateStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStorageConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateStorageConfigRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *CreateStorageConfigRequest) GetPurpose() string {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return ""
}

func (x *CreateStorageConfigRequest) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *CreateStorageConfigRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *CreateStorageConfigRequest) GetConfigJson() string {
	if x != nil && x.ConfigJson != nil {
		return *x.ConfigJson
	}
	return ""
}

type CreateStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageConfig *StorageConfig         `protobuf:"bytes,1,opt,name=storage_config,json=storageConfig,proto3" json:"storage_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStorageConfigResponse) Reset() {
	*x = CreateStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageConfigResponse) ProtoMessage() {}

func (x *CreateStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStorageConfigResponse) GetStorageConfig() *StorageConfig {
	if x != nil {
		return x.StorageConfig
	}
	return nil
}

type UpdateStorageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Provider      *string                `protobuf:"bytes,3,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Purpose       *string                `protobuf:"bytes,4,opt,name=purpose,proto3,oneof" json:"purpose,omitempty"`
	Bucket        *string                `protobuf:"bytes,5,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	IsDefault     *bool                  `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	ConfigJson    *string                `protobuf:"bytes,7,opt,name=config_json,json=configJson,proto3,oneof" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageConfigRequest) Reset() {
	*x = UpdateStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageConfigRequest) ProtoMessage() {}

func (x *UpdateStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStorageConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStorageConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateStorageConfigRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *UpdateStorageConfigRequest) GetPurpose() string {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return ""
}

func (x *UpdateStorageConfigRequest) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *UpdateStorageConfigRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *UpdateStorageConfigRequest) GetConfigJson() string {
	if x != nil && x.ConfigJson != nil {
		return *x.ConfigJson
	}
	return ""
}

type UpdateStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageConfig *StorageConfig         `protobuf:"bytes,1,opt,name=storage_config,json=storageConfig,proto3" json:"storage_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageConfigResponse) Reset() {
	*x = UpdateStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageConfigResponse) ProtoMessage() {}

func (x *UpdateStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStorageConfigResponse) GetStorageConfig() *StorageConfig {
	if x != nil {
		return x.StorageConfig
	}
	return nil
}

type DeleteStorageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStorageConfigRequest) Reset() {
	*x = DeleteStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageConfigRequest) ProtoMessage() {}

func (x *DeleteStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStorageConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStorageConfigResponse) Reset() {
	*x = DeleteStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageConfigResponse) ProtoMessage() {}

func (x *DeleteStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{6}
}

type GetStorageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageConfigRequest) Reset() {
	*x = GetStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageConfigRequest) ProtoMessage() {}

func (x *GetStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*GetStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetStorageConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageConfig *StorageConfig         `protobuf:"bytes,1,opt,name=storage_config,json=storageConfig,proto3" json:"storage_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageConfigResponse) Reset() {
	*x = GetStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageConfigResponse) ProtoMessage() {}

func (x *GetStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*GetStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{8}
}

func (x *GetStorageConfigResponse) GetStorageConfig() *StorageConfig {
	if x != nil {
		return x.StorageConfig
	}
	return nil
}

type ListStorageConfigsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页
	PageSize *int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// 分页token
	PageToken *string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// 过滤条件
	Filter *string `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// 排序条件
	OrderBy       *string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageConfigsRequest) Reset() {
	*x = ListStorageConfigsRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageConfigsRequest) ProtoMessage() {}

func (x *ListStorageConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListStorageConfigsRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{9}
}

func (x *ListStorageConfigsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListStorageConfigsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListStorageConfigsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ListStorageConfigsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

type ListStorageConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StorageConfig       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPageToken *string                `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageConfigsResponse) Reset() {
	*x = ListStorageConfigsResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageConfigsResponse) ProtoMessage() {}

func (x *ListStorageConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListStorageConfigsResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{10}
}

func (x *ListStorageConfigsResponse) GetItems() []*StorageConfig {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListStorageConfigsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStorageConfigsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type SetDefaultStorageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultStorageConfigRequest) Reset() {
	*x = SetDefaultStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultStorageConfigRequest) ProtoMessage() {}

func (x *SetDefaultStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{11}
}

func (x *SetDefaultStorageConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetDefaultStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultStorageConfigResponse) Reset() {
	*x = SetDefaultStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultStorageConfigResponse) ProtoMessage() {}

func (x *SetDefaultStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{12}
}

type TestStorageConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 已有配置ID
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 或内联测试配置
	Provider      *string `protobuf:"bytes,2,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	ConfigJson    *string `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3,oneof" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStorageConfigRequest) Reset() {
	*x = TestStorageConfigRequest{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStorageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStorageConfigRequest) ProtoMessage() {}

func (x *TestStorageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStorageConfigRequest.ProtoReflect.Descriptor instead.
func (*TestStorageConfigRequest) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{13}
}

func (x *TestStorageConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestStorageConfigRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *TestStorageConfigRequest) GetConfigJson() string {
	if x != nil && x.ConfigJson != nil {
		return *x.ConfigJson
	}
	return ""
}

type TestStorageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStorageConfigResponse) Reset() {
	*x = TestStorageConfigResponse{}
	mi := &file_core_service_v1_storage_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStorageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStorageConfigResponse) ProtoMessage() {}

func (x *TestStorageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_v1_storage_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStorageConfigResponse.ProtoReflect.Descriptor instead.
func (*TestStorageConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_service_v1_storage_config_proto_rawDescGZIP(), []int{14}
}

func (x *TestStorageConfigResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *TestStorageConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_core_service_v1_storage_config_proto protoreflect.FileDescriptor

const file_core_service_v1_storage_config_proto_rawDesc = "" +
	"\n" +
	"$core/service/v1/storage_config.proto\x12\x0fcore.service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/enum/enum.proto\x1a\"common/pagination/pagination.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\a\n" +
	"\rStorageConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x124\n" +
	"\x04name\x18\x02 \x01(\tB\x1b\xbaG\x0f\x92\x02\f配置名称\xbaH\x06r\x04\x10\x01\x18xH\x00R\x04name\x88\x01\x01\x12\xb1\x01\n" +
	"\bprovider\x18\x03 \x01(\tB\x8f\x01\xbaGH\x92\x02E存储供应商 s3-compatible/aliyun-oss/tencent-cos/qiniu-kodo/local\xbaHAr?\x10\x01\x18(R\rs3-compatibleR\n" +
	"aliyun-ossR\vtencent-cosR\n" +
	"qiniu-kodoR\x05localH\x01R\bprovider\x88\x01\x01\x12G\n" +
	"\apurpose\x18\x04 \x01(\tB(\xbaG\x1e\x92\x02\x1b用途 default/audio/backup\xbaH\x04r\x02\x18(H\x02R\apurpose\x88\x01\x01\x126\n" +
	"\x06bucket\x18\x05 \x01(\tB\x19\xbaG\x0f\x92\x02\f默认桶名\xbaH\x04r\x02\x18xH\x03R\x06bucket\x88\x01\x01\x12<\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bB\x18\xbaG\x15\x92\x02\x12是否默认存储H\x04R\tisDefault\x88\x01\x01\x12^\n" +
	"\vconfig_json\x18\a \x01(\tB8\xbaG.\x92\x02+供应商专属配置JSON（加密传输）\xbaH\x04r\x02\x10\x01H\x05R\n" +
	"configJson\x88\x01\x01\x12z\n" +
	"\rhealth_status\x18\b \x01(\tBP\xbaG)\x92\x02&健康状态 unknown/healthy/unhealthy\xbaH!r\x1f\x18\x14R\aunknownR\ahealthyR\tunhealthyH\x06R\fhealthStatus\x88\x01\x01\x126\n" +
	"\n" +
	"created_at\x18\t \x01(\tB\x12\xbaG\x0f\x92\x02\f创建时间H\aR\tcreatedAt\x88\x01\x01\x126\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tB\x12\xbaG\x0f\x92\x02\f更新时间H\bR\tupdatedAt\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_providerB\n" +
	"\n" +
	"\b_purposeB\t\n" +
	"\a_bucketB\r\n" +
	"\v_is_defaultB\x0e\n" +
	"\f_config_jsonB\x10\n" +
	"\x0e_health_statusB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"\xa7\x04\n" +
	"\x1aCreateStorageConfigRequest\x124\n" +
	"\x04name\x18\x01 \x01(\tB\x1b\xbaG\x0f\x92\x02\f配置名称\xbaH\x06r\x04\x10\x01\x18xH\x00R\x04name\x88\x01\x01\x12z\n" +
	"\bprovider\x18\x02 \x01(\tBY\xbaG\x12\x92\x02\x0f存储供应商\xbaHAr?\x10\x01\x18(R\rs3-compatibleR\n" +
	"aliyun-ossR\vtencent-cosR\n" +
	"qiniu-kodoR\x05localH\x01R\bprovider\x88\x01\x01\x12G\n" +
	"\apurpose\x18\x03 \x01(\tB(\xbaG\x1e\x92\x02\x1b用途 default/audio/backup\xbaH\x04r\x02\x18(H\x02R\apurpose\x88\x01\x01\x126\n" +
	"\x06bucket\x18\x04 \x01(\tB\x19\xbaG\x0f\x92\x02\f默认桶名\xbaH\x04r\x02\x18xH\x03R\x06bucket\x88\x01\x01\x12<\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bB\x18\xbaG\x15\x92\x02\x12是否默认存储H\x04R\tisDefault\x88\x01\x01\x12L\n" +
	"\vconfig_json\x18\x06 \x01(\tB&\xbaG\x1c\x92\x02\x19供应商专属配置JSON\xbaH\x04r\x02\x10\x01H\x05R\n" +
	"configJson\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_providerB\n" +
	"\n" +
	"\b_purposeB\t\n" +
	"\a_bucketB\r\n" +
	"\v_is_defaultB\x0e\n" +
	"\f_config_json\"d\n" +
	"\x1bCreateStorageConfigResponse\x12E\n" +
	"\x0estorage_config\x18\x01 \x01(\v2\x1e.core.service.v1.StorageConfigR\rstorageConfig\"\xae\x04\n" +
	"\x1aUpdateStorageConfigRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b配置ID\xbaH\x04*\x02(\x01R\x02id\x122\n" +
	"\x04name\x18\x02 \x01(\tB\x19\xbaG\x0f\x92\x02\f配置名称\xbaH\x04r\x02\x18xH\x00R\x04name\x88\x01\x01\x12x\n" +
	"\bprovider\x18\x03 \x01(\tBW\xbaG\x12\x92\x02\x0f存储供应商\xbaH?r=\x18(R\rs3-compatibleR\n" +
	"aliyun-ossR\vtencent-cosR\n" +
	"qiniu-kodoR\x05localH\x01R\bprovider\x88\x01\x01\x122\n" +
	"\apurpose\x18\x04 \x01(\tB\x13\xbaG\t\x92\x02\x06用途\xbaH\x04r\x02\x18(H\x02R\apurpose\x88\x01\x01\x126\n" +
	"\x06bucket\x18\x05 \x01(\tB\x19\xbaG\x0f\x92\x02\f默认桶名\xbaH\x04r\x02\x18xH\x03R\x06bucket\x88\x01\x01\x12<\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bB\x18\xbaG\x15\x92\x02\x12是否默认存储H\x04R\tisDefault\x88\x01\x01\x12E\n" +
	"\vconfig_json\x18\a \x01(\tB\x1f\xbaG\x1c\x92\x02\x19供应商专属配置JSONH\x05R\n" +
	"configJson\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_providerB\n" +
	"\n" +
	"\b_purposeB\t\n" +
	"\a_bucketB\r\n" +
	"\v_is_defaultB\x0e\n" +
	"\f_config_json\"d\n" +
	"\x1bUpdateStorageConfigResponse\x12E\n" +
	"\x0estorage_config\x18\x01 \x01(\v2\x1e.core.service.v1.StorageConfigR\rstorageConfig\"C\n" +
	"\x1aDeleteStorageConfigRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b配置ID\xbaH\x04*\x02(\x01R\x02id\"\x1d\n" +
	"\x1bDeleteStorageConfigResponse\"@\n" +
	"\x17GetStorageConfigRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b配置ID\xbaH\x04*\x02(\x01R\x02id\"a\n" +
	"\x18GetStorageConfigResponse\x12E\n" +
	"\x0estorage_config\x18\x01 \x01(\v2\x1e.core.service.v1.StorageConfigR\rstorageConfig\"\xb7\x02\n" +
	"\x19ListStorageConfigsRequest\x12I\n" +
	"\tpage_size\x18\x01 \x01(\x05B'\xbaG\x1b\x8a\x02\t\t\x00\x00\x00\x00\x00\x004@\x92\x02\f每页数量\xbaH\x06\x1a\x04\x18d(\x01H\x00R\bpageSize\x88\x01\x01\x125\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x11\xbaG\x0e\x92\x02\v分页tokenH\x01R\tpageToken\x88\x01\x01\x12/\n" +
	"\x06filter\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f过滤条件H\x02R\x06filter\x88\x01\x01\x122\n" +
	"\border_by\x18\x04 \x01(\tB\x12\xbaG\x0f\x92\x02\f排序条件H\x03R\aorderBy\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\t\n" +
	"\a_filterB\v\n" +
	"\t_order_by\"\xa9\x01\n" +
	"\x1aListStorageConfigsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.core.service.v1.StorageConfigR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12+\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"G\n" +
	"\x1eSetDefaultStorageConfigRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b配置ID\xbaH\x04*\x02(\x01R\x02id\"!\n" +
	"\x1fSetDefaultStorageConfigResponse\"\x9b\x02\n" +
	"\x18TestStorageConfigRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\rB\x14\xbaG\x11\x92\x02\x0e已有配置IDR\x02id\x12~\n" +
	"\bprovider\x18\x02 \x01(\tB]\xbaG\x18\x92\x02\x15测试存储供应商\xbaH?r=\x18(R\rs3-compatibleR\n" +
	"aliyun-ossR\vtencent-cosR\n" +
	"qiniu-kodoR\x05localH\x00R\bprovider\x88\x01\x01\x12<\n" +
	"\vconfig_json\x18\x03 \x01(\tB\x16\xbaG\x13\x92\x02\x10测试配置JSONH\x01R\n" +
	"configJson\x88\x01\x01B\v\n" +
	"\t_providerB\x0e\n" +
	"\f_config_json\"O\n" +
	"\x19TestStorageConfigResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xae\x06\n" +
	"\x14StorageConfigService\x12p\n" +
	"\x13CreateStorageConfig\x12+.core.service.v1.CreateStorageConfigRequest\x1a,.core.service.v1.CreateStorageConfigResponse\x12p\n" +
	"\x13UpdateStorageConfig\x12+.core.service.v1.UpdateStorageConfigRequest\x1a,.core.service.v1.UpdateStorageConfigResponse\x12p\n" +
	"\x13DeleteStorageConfig\x12+.core.service.v1.DeleteStorageConfigRequest\x1a,.core.service.v1.DeleteStorageConfigResponse\x12g\n" +
	"\x10GetStorageConfig\x12(.core.service.v1.GetStorageConfigRequest\x1a).core.service.v1.GetStorageConfigResponse\x12m\n" +
	"\x12ListStorageConfigs\x12*.core.service.v1.ListStorageConfigsRequest\x1a+.core.service.v1.ListStorageConfigsResponse\x12|\n" +
	"\x17SetDefaultStorageConfig\x12/.core.service.v1.SetDefaultStorageConfigRequest\x1a0.core.service.v1.SetDefaultStorageConfigResponse\x12j\n" +
	"\x11TestStorageConfig\x12).core.service.v1.TestStorageConfigRequest\x1a*.core.service.v1.TestStorageConfigResponseB\xaf\x01\n" +
	"\x13com.core.service.v1B\x12StorageConfigProtoP\x01Z&backend-service/api/core/service/v1;v1\xa2\x02\x03CSX\xaa\x02\x0fCore.Service.V1\xca\x02\x0fCore\\Service\\V1\xe2\x02\x1bCore\\Service\\V1\\GPBMetadata\xea\x02\x11Core::Service::V1b\x06proto3"

var (
	file_core_service_v1_storage_config_proto_rawDescOnce sync.Once
	file_core_service_v1_storage_config_proto_rawDescData []byte
)

func file_core_service_v1_storage_config_proto_rawDescGZIP() []byte {
	file_core_service_v1_storage_config_proto_rawDescOnce.Do(func() {
		file_core_service_v1_storage_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_service_v1_storage_config_proto_rawDesc), len(file_core_service_v1_storage_config_proto_rawDesc)))
	})
	return file_core_service_v1_storage_config_proto_rawDescData
}

var file_core_service_v1_storage_config_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_core_service_v1_storage_config_proto_goTypes = []any{
	(*StorageConfig)(nil),                   // 0: core.service.v1.StorageConfig
	(*CreateStorageConfigRequest)(nil),      // 1: core.service.v1.CreateStorageConfigRequest
	(*CreateStorageConfigResponse)(nil),     // 2: core.service.v1.CreateStorageConfigResponse
	(*UpdateStorageConfigRequest)(nil),      // 3: core.service.v1.UpdateStorageConfigRequest
	(*UpdateStorageConfigResponse)(nil),     // 4: core.service.v1.UpdateStorageConfigResponse
	(*DeleteStorageConfigRequest)(nil),      // 5: core.service.v1.DeleteStorageConfigRequest
	(*DeleteStorageConfigResponse)(nil),     // 6: core.service.v1.DeleteStorageConfigResponse
	(*GetStorageConfigRequest)(nil),         // 7: core.service.v1.GetStorageConfigRequest
	(*GetStorageConfigResponse)(nil),        // 8: core.service.v1.GetStorageConfigResponse
	(*ListStorageConfigsRequest)(nil),       // 9: core.service.v1.ListStorageConfigsRequest
	(*ListStorageConfigsResponse)(nil),      // 10: core.service.v1.ListStorageConfigsResponse
	(*SetDefaultStorageConfigRequest)(nil),  // 11: core.service.v1.SetDefaultStorageConfigRequest
	(*SetDefaultStorageConfigResponse)(nil), // 12: core.service.v1.SetDefaultStorageConfigResponse
	(*TestStorageConfigRequest)(nil),        // 13: core.service.v1.TestStorageConfigRequest
	(*TestStorageConfigResponse)(nil),       // 14: core.service.v1.TestStorageConfigResponse
}
var file_core_service_v1_storage_config_proto_depIdxs = []int32{
	0,  // 0: core.service.v1.CreateStorageConfigResponse.storage_config:type_name -> core.service.v1.StorageConfig
	0,  // 1: core.service.v1.UpdateStorageConfigResponse.storage_config:type_name -> core.service.v1.StorageConfig
	0,  // 2: core.service.v1.GetStorageConfigResponse.storage_config:type_name -> core.service.v1.StorageConfig
	0,  // 3: core.service.v1.ListStorageConfigsResponse.items:type_name -> core.service.v1.StorageConfig
	1,  // 4: core.service.v1.StorageConfigService.CreateStorageConfig:input_type -> core.service.v1.CreateStorageConfigRequest
	3,  // 5: core.service.v1.StorageConfigService.UpdateStorageConfig:input_type -> core.service.v1.UpdateStorageConfigRequest
	5,  // 6: core.service.v1.StorageConfigService.DeleteStorageConfig:input_type -> core.service.v1.DeleteStorageConfigRequest
	7,  // 7: core.service.v1.StorageConfigService.GetStorageConfig:input_type -> core.service.v1.GetStorageConfigRequest
	9,  // 8: core.service.v1.StorageConfigService.ListStorageConfigs:input_type -> core.service.v1.ListStorageConfigsRequest
	11, // 9: core.service.v1.StorageConfigService.SetDefaultStorageConfig:input_type -> core.service.v1.SetDefaultStorageConfigRequest
	13, // 10: core.service.v1.StorageConfigService.TestStorageConfig:input_type -> core.service.v1.TestStorageConfigRequest
	2,  // 11: core.service.v1.StorageConfigService.CreateStorageConfig:output_type -> core.service.v1.CreateStorageConfigResponse
	4,  // 12: core.service.v1.StorageConfigService.UpdateStorageConfig:output_type -> core.service.v1.UpdateStorageConfigResponse
	6,  // 13: core.service.v1.StorageConfigService.DeleteStorageConfig:output_type -> core.service.v1.DeleteStorageConfigResponse
	8,  // 14: core.service.v1.StorageConfigService.GetStorageConfig:output_type -> core.service.v1.GetStorageConfigResponse
	10, // 15: core.service.v1.StorageConfigService.ListStorageConfigs:output_type -> core.service.v1.ListStorageConfigsResponse
	12, // 16: core.service.v1.StorageConfigService.SetDefaultStorageConfig:output_type -> core.service.v1.SetDefaultStorageConfigResponse
	14, // 17: core.service.v1.StorageConfigService.TestStorageConfig:output_type -> core.service.v1.TestStorageConfigResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_core_service_v1_storage_config_proto_init() }
func file_core_service_v1_storage_config_proto_init() {
	if File_core_service_v1_storage_config_proto != nil {
		return
	}
	file_core_service_v1_storage_config_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_service_v1_storage_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_core_service_v1_storage_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_core_service_v1_storage_config_proto_msgTypes[9].OneofWrappers = []any{}
	file_core_service_v1_storage_config_proto_msgTypes[10].OneofWrappers = []any{}
	file_core_service_v1_storage_config_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_v1_storage_config_proto_rawDesc), len(file_core_service_v1_storage_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_v1_storage_config_proto_goTypes,
		DependencyIndexes: file_core_service_v1_storage_config_proto_depIdxs,
		MessageInfos:      file_core_service_v1_storage_config_proto_msgTypes,
	}.Build()
	File_core_service_v1_storage_config_proto = out.File
	file_core_service_v1_storage_config_proto_goTypes = nil
	file_core_service_v1_storage_config_proto_depIdxs = nil
}
