syntax = "proto3";

package conf;

option go_package = "backend-service/api/common/conf;conf";

import "google/protobuf/duration.proto";
import "common/conf/middleware.proto";

// 客户端
message Client {
  // HTTP
  message HTTP {
    string addr = 1; // 服务地址
    google.protobuf.Duration timeout = 2; // 超时时间
    Middleware middleware = 3;
  }

  // gPRC
  message GRPC {
    string addr = 1; // 服务地址
    google.protobuf.Duration timeout = 2; // 超时时间
    Middleware middleware = 3;
  }

  HTTP http = 1;  // HTTP服务
  GRPC grpc = 2;  // gRPC服务
}
