// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: evie/tool/v1/enhancement.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnhancementService_EnhanceText_FullMethodName = "/evie.tool.v1.EnhancementService/EnhanceText"
)

// EnhancementServiceClient is the client API for EnhancementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnhancementService 纯文本增强（不调 ASR）。
type EnhancementServiceClient interface {
	EnhanceText(ctx context.Context, in *EnhanceTextRequest, opts ...grpc.CallOption) (*EnhanceTextResponse, error)
}

type enhancementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnhancementServiceClient(cc grpc.ClientConnInterface) EnhancementServiceClient {
	return &enhancementServiceClient{cc}
}

func (c *enhancementServiceClient) EnhanceText(ctx context.Context, in *EnhanceTextRequest, opts ...grpc.CallOption) (*EnhanceTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnhanceTextResponse)
	err := c.cc.Invoke(ctx, EnhancementService_EnhanceText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnhancementServiceServer is the server API for EnhancementService service.
// All implementations must embed UnimplementedEnhancementServiceServer
// for forward compatibility.
//
// EnhancementService 纯文本增强（不调 ASR）。
type EnhancementServiceServer interface {
	EnhanceText(context.Context, *EnhanceTextRequest) (*EnhanceTextResponse, error)
	mustEmbedUnimplementedEnhancementServiceServer()
}

// UnimplementedEnhancementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnhancementServiceServer struct{}

func (UnimplementedEnhancementServiceServer) EnhanceText(context.Context, *EnhanceTextRequest) (*EnhanceTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnhanceText not implemented")
}
func (UnimplementedEnhancementServiceServer) mustEmbedUnimplementedEnhancementServiceServer() {}
func (UnimplementedEnhancementServiceServer) testEmbeddedByValue()                            {}

// UnsafeEnhancementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnhancementServiceServer will
// result in compilation errors.
type UnsafeEnhancementServiceServer interface {
	mustEmbedUnimplementedEnhancementServiceServer()
}

func RegisterEnhancementServiceServer(s grpc.ServiceRegistrar, srv EnhancementServiceServer) {
	// If the following call panics, it indicates UnimplementedEnhancementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnhancementService_ServiceDesc, srv)
}

func _EnhancementService_EnhanceText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnhanceTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnhancementServiceServer).EnhanceText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnhancementService_EnhanceText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnhancementServiceServer).EnhanceText(ctx, req.(*EnhanceTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnhancementService_ServiceDesc is the grpc.ServiceDesc for EnhancementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnhancementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evie.tool.v1.EnhancementService",
	HandlerType: (*EnhancementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnhanceText",
			Handler:    _EnhancementService_EnhanceText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evie/tool/v1/enhancement.proto",
}

const (
	AdminService_GetVocabSyncStatus_FullMethodName = "/evie.tool.v1.AdminService/GetVocabSyncStatus"
	AdminService_TriggerVocabSync_FullMethodName   = "/evie.tool.v1.AdminService/TriggerVocabSync"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService 运维接口（同步状态查询 + 手动触发）。
type AdminServiceClient interface {
	GetVocabSyncStatus(ctx context.Context, in *GetVocabSyncStatusRequest, opts ...grpc.CallOption) (*GetVocabSyncStatusResponse, error)
	TriggerVocabSync(ctx context.Context, in *TriggerVocabSyncRequest, opts ...grpc.CallOption) (*TriggerVocabSyncResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetVocabSyncStatus(ctx context.Context, in *GetVocabSyncStatusRequest, opts ...grpc.CallOption) (*GetVocabSyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVocabSyncStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetVocabSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TriggerVocabSync(ctx context.Context, in *TriggerVocabSyncRequest, opts ...grpc.CallOption) (*TriggerVocabSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerVocabSyncResponse)
	err := c.cc.Invoke(ctx, AdminService_TriggerVocabSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService 运维接口（同步状态查询 + 手动触发）。
type AdminServiceServer interface {
	GetVocabSyncStatus(context.Context, *GetVocabSyncStatusRequest) (*GetVocabSyncStatusResponse, error)
	TriggerVocabSync(context.Context, *TriggerVocabSyncRequest) (*TriggerVocabSyncResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetVocabSyncStatus(context.Context, *GetVocabSyncStatusRequest) (*GetVocabSyncStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVocabSyncStatus not implemented")
}
func (UnimplementedAdminServiceServer) TriggerVocabSync(context.Context, *TriggerVocabSyncRequest) (*TriggerVocabSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerVocabSync not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetVocabSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVocabSyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetVocabSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetVocabSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetVocabSyncStatus(ctx, req.(*GetVocabSyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TriggerVocabSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerVocabSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TriggerVocabSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TriggerVocabSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TriggerVocabSync(ctx, req.(*TriggerVocabSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evie.tool.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVocabSyncStatus",
			Handler:    _AdminService_GetVocabSyncStatus_Handler,
		},
		{
			MethodName: "TriggerVocabSync",
			Handler:    _AdminService_TriggerVocabSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evie/tool/v1/enhancement.proto",
}
