syntax = "proto3";

package platform.admin.v1;

import "core/service/v1/device.proto";
import "google/api/annotations.proto";

option go_package = "backend-service/api/platform/admin/v1;v1";

service DeviceService {
  rpc RegisterDevice(core.service.v1.RegisterDeviceRequest) returns (core.service.v1.Device) {
    option (google.api.http) = {
      post: "/admin/v1/my/devices"
      body: "*"
    };
  }
  rpc UnregisterDevice(core.service.v1.UnregisterDeviceRequest) returns (core.service.v1.UnregisterDeviceResponse) {
    option (google.api.http) = {
      delete: "/admin/v1/my/devices/{device_token}"
    };
  }
  rpc ListMyDevices(core.service.v1.ListMyDevicesRequest) returns (core.service.v1.ListMyDevicesResponse) {
    option (google.api.http) = {get: "/admin/v1/my/devices"};
  }
  rpc ListUserDevices(core.service.v1.ListUserDevicesRequest) returns (core.service.v1.ListUserDevicesResponse) {
    option (google.api.http) = {get: "/admin/v1/users/{user_id}/devices"};
  }
}
