syntax = "proto3";

package platform.admin.v1;

import "core/service/v1/login_log.proto";
import "google/api/annotations.proto";

option go_package = "backend-service/api/platform/admin/v1;v1";

service LoginLogService {
  rpc ListLoginLogs(core.service.v1.ListLoginLogsRequest) returns (core.service.v1.ListLoginLogsResponse) {
    option (google.api.http) = {get: "/admin/v1/login-logs"};
  }

  rpc GetLoginLog(core.service.v1.GetLoginLogRequest) returns (core.service.v1.LoginLog) {
    option (google.api.http) = {get: "/admin/v1/login-logs/{id}"};
  }
}

