syntax = "proto3";

package platform.admin.v1;

import "core/service/v1/project.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

option go_package = "backend-service/api/platform/admin/v1;v1";

// 项目管理服务
service ProjectService {
  // 获取项目列表
  rpc ListProjects(core.service.v1.ListProjectsRequest) returns (core.service.v1.ListProjectsResponse) {
    option (google.api.http) = {get: "/admin/v1/projects"};
    option (gnostic.openapi.v3.operation) = {
      summary: "获取项目列表"
      description: "获取项目列表"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }

  // 获取项目数据
  rpc GetProject(core.service.v1.GetProjectRequest) returns (core.service.v1.Project) {
    option (google.api.http) = {get: "/admin/v1/projects/{id}"};
    option (gnostic.openapi.v3.operation) = {
      summary: "获取项目数据"
      description: "获取项目数据"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }

  // 创建项目
  rpc CreateProject(core.service.v1.CreateProjectRequest) returns (core.service.v1.CreateProjectResponse) {
    option (google.api.http) = {
      post: "/admin/v1/projects"
      body: "project"
    };
    option (gnostic.openapi.v3.operation) = {
      summary: "创建项目"
      description: "创建项目"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }

  // 更新项目
  rpc UpdateProject(core.service.v1.UpdateProjectRequest) returns (core.service.v1.UpdateProjectResponse) {
    option (google.api.http) = {
      put: "/admin/v1/projects/{id}"
      body: "project"
    };
    option (gnostic.openapi.v3.operation) = {
      summary: "更新项目"
      description: "更新项目"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }

  // 删除项目
  rpc DeleteProject(core.service.v1.DeleteProjectRequest) returns (core.service.v1.DeleteProjectResponse) {
    option (google.api.http) = {delete: "/admin/v1/projects/{id}"};
    option (gnostic.openapi.v3.operation) = {
      summary: "删除项目"
      description: "删除项目"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }

  // 更新项目状态
  rpc UpdateProjectByStatus(core.service.v1.UpdateProjectByStatusRequest) returns (core.service.v1.UpdateProjectByStatusResponse) {
    option (google.api.http) = {
      put: "/admin/v1/projects/status-update/{id}"
      body: "status"
    };
    option (gnostic.openapi.v3.operation) = {
      summary: "更新项目状态"
      description: "更新项目状态"
      tags: ["项目管理服务"]
      security: [
        {
          additional_properties: [
            {
              name: "BearerAuth"
              value: {}
            }
          ]
        }
      ]
    };
  }
}
