syntax = "proto3";

package platform.admin.v1;

import "core/service/v1/session.proto";
import "google/api/annotations.proto";

option go_package = "backend-service/api/platform/admin/v1;v1";

service SessionService {
  rpc ListSessions(core.service.v1.ListSessionsRequest) returns (core.service.v1.ListSessionsResponse) {
    option (google.api.http) = {get: "/admin/v1/sessions"};
  }

  rpc ListMySessions(core.service.v1.ListMySessionsRequest) returns (core.service.v1.ListMySessionsResponse) {
    option (google.api.http) = {get: "/admin/v1/sessions/mine"};
  }

  rpc RevokeSession(core.service.v1.RevokeSessionRequest) returns (core.service.v1.RevokeSessionResponse) {
    option (google.api.http) = {delete: "/admin/v1/sessions/{id}"};
  }
}

