syntax = "proto3";

package platform.admin.v1;

import "core/service/v1/storage_provider.proto";
import "google/api/annotations.proto";

option go_package = "backend-service/api/platform/admin/v1;v1";
option java_multiple_files = true;
option java_package = "platform.admin.v1";

service StorageProviderService {
  rpc CreateStorageProvider(core.service.v1.CreateStorageProviderRequest) returns (core.service.v1.CreateStorageProviderResponse) {
    option (google.api.http) = {
      post: "/admin/v1/storage-providers"
      body: "*"
    };
  }
  rpc UpdateStorageProvider(core.service.v1.UpdateStorageProviderRequest) returns (core.service.v1.UpdateStorageProviderResponse) {
    option (google.api.http) = {
      put: "/admin/v1/storage-providers/{id}"
      body: "*"
    };
  }
  rpc DeleteStorageProvider(core.service.v1.DeleteStorageProviderRequest) returns (core.service.v1.DeleteStorageProviderResponse) {
    option (google.api.http) = {delete: "/admin/v1/storage-providers/{id}"};
  }
  rpc GetStorageProvider(core.service.v1.GetStorageProviderRequest) returns (core.service.v1.StorageProvider) {
    option (google.api.http) = {get: "/admin/v1/storage-providers/{id}"};
  }
  rpc ListStorageProviders(core.service.v1.ListStorageProvidersRequest) returns (core.service.v1.ListStorageProvidersResponse) {
    option (google.api.http) = {get: "/admin/v1/storage-providers"};
  }
  rpc SetDefaultStorageProvider(core.service.v1.SetDefaultStorageProviderRequest) returns (core.service.v1.SetDefaultStorageProviderResponse) {
    option (google.api.http) = {
      post: "/admin/v1/storage-providers/{id}:set-default"
      body: "*"
    };
  }
  rpc TestStorageProvider(core.service.v1.TestStorageProviderRequest) returns (core.service.v1.TestStorageProviderResponse) {
    option (google.api.http) = {
      post: "/admin/v1/storage-providers:test"
      body: "*"
    };
  }
}
