// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/service/v1/i_chat.proto

package v1

import (
	enum "backend-service/api/common/enum"
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status        *enum.Status           `protobuf:"varint,11,opt,name=status,proto3,enum=enum.Status,oneof" json:"status,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	Description   *string                `protobuf:"bytes,14,opt,name=description,proto3,oneof" json:"description,omitempty"` // 个人说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chat) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Chat) GetStatus() enum.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return enum.Status(0)
}

func (x *Chat) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *Chat) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

func (x *Chat) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatRequest) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *CreateChatRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{2}
}

type UpdateChatRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Chat       *Chat                  `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
	OperatorId *uint32                `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	// Required. Mask of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateChatRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChatRequest) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *UpdateChatRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *UpdateChatRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatResponse) Reset() {
	*x = UpdateChatResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatResponse) ProtoMessage() {}

func (x *UpdateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{4}
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChatRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteChatRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{6}
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ListChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每页的行数
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 当前页码
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// 是否不分页
	NoPaging *bool        `protobuf:"varint,3,opt,name=no_paging,json=nopaging,proto3,oneof" json:"no_paging,omitempty"`
	Status   *enum.Status `protobuf:"varint,6,opt,name=status,proto3,enum=enum.Status,oneof" json:"status,omitempty"`
	// Optional. The standard list filter.
	// Supported fields:
	//   - `name` (i.e. `name="John Doe"`)
	//   - `email` (i.e. `email="admin@go-kratos.dev"`)
	//   - `phone` (i.e. `phone="+1234567890"`)
	//   - `create_time` range (i.e. `timestamp>="2025-01-31T11:30:00-04:00"` where
	//     the timestamp is in RFC 3339 format)
	//
	// More detail in [AIP-160](https://google.aip.dev/160).
	Filter *string `protobuf:"bytes,10,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to order by, sorted in ascending
	// order. Use "desc" after a field name for descending. Supported fields:
	// - `create_time`
	//
	// Example: `create_time desc`.
	OrderBy *string `protobuf:"bytes,11,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"` // Number of resource to skip in the request.
	//   - A request with no page token and a skip value of 30 returns a single
	//     page of results starting with the 31st result.
	//   - A request with a page token corresponding to the 51st result (because the
	//     first 50 results were returned on the first page) and a skip value of 30
	//     returns a single page of results starting with the 81st result.
	Skip          int32 `protobuf:"varint,12,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChatsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListChatsRequest) GetNoPaging() bool {
	if x != nil && x.NoPaging != nil {
		return *x.NoPaging
	}
	return false
}

func (x *ListChatsRequest) GetStatus() enum.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return enum.Status(0)
}

func (x *ListChatsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ListChatsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListChatsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Chat                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ListChatsResponse) GetItems() []*Chat {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListChatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChatsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 更新对话状态 - 请求
type UpdateChatByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *enum.Status           `protobuf:"varint,2,opt,name=status,proto3,enum=enum.Status,oneof" json:"status,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatByStatusRequest) Reset() {
	*x = UpdateChatByStatusRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatByStatusRequest) ProtoMessage() {}

func (x *UpdateChatByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatByStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatByStatusRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateChatByStatusRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChatByStatusRequest) GetStatus() enum.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return enum.Status(0)
}

func (x *UpdateChatByStatusRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// 更新对话状态 - 回应
type UpdateChatByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatByStatusResponse) Reset() {
	*x = UpdateChatByStatusResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatByStatusResponse) ProtoMessage() {}

func (x *UpdateChatByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatByStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatByStatusResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{12}
}

type StreamChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint32                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatRequest) Reset() {
	*x = StreamChatRequest{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatRequest) ProtoMessage() {}

func (x *StreamChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatRequest.ProtoReflect.Descriptor instead.
func (*StreamChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{13}
}

func (x *StreamChatRequest) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *StreamChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatResponse) Reset() {
	*x = StreamChatResponse{}
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatResponse) ProtoMessage() {}

func (x *StreamChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v1_i_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatResponse.ProtoReflect.Descriptor instead.
func (*StreamChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v1_i_chat_proto_rawDescGZIP(), []int{14}
}

func (x *StreamChatResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

var File_ai_service_v1_i_chat_proto protoreflect.FileDescriptor

const file_ai_service_v1_i_chat_proto_rawDesc = "" +
	"\n" +
	"\x1aai/service/v1/i_chat.proto\x12\rai.service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/enum/enum.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\"\xa4\x03\n" +
	"\x04Chat\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\rB\x0e\xbaG\v\x92\x02\b对话IDR\x02id\x121\n" +
	"\x04name\x18\x02 \x01(\tB\x18\xbaG\f\x92\x02\t对话名\xbaH\x06r\x04\x10\x01\x18\x14H\x00R\x04name\x88\x01\x01\x12\\\n" +
	"\x06status\x18\v \x01(\x0e2\f.enum.StatusB1\xbaG$\x92\x02!状态 0 未知 1 启用 2 禁用\xbaH\a\x82\x01\x04\x10\x01 \x00H\x01R\x06status\x88\x01\x01\x126\n" +
	"\n" +
	"created_at\x18\f \x01(\tB\x12\xbaG\x0f\x92\x02\f创建时间H\x02R\tcreatedAt\x88\x01\x01\x126\n" +
	"\n" +
	"updated_at\x18\r \x01(\tB\x12\xbaG\x0f\x92\x02\f更新时间H\x03R\tupdatedAt\x88\x01\x01\x129\n" +
	"\vdescription\x18\x0e \x01(\tB\x12\xbaG\x0f\x92\x02\f个人说明H\x04R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_statusB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\x0e\n" +
	"\f_description\"\xa6\x01\n" +
	"\x11CreateChatRequest\x12A\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.ai.service.v1.ChatB\x18\xbaG\x0f\x92\x02\f对话信息\xbaH\x03\xc8\x01\x01R\x04chat\x12>\n" +
	"\voperator_id\x18\x02 \x01(\rB\x18\xbaG\x0e\x92\x02\v操作人ID\xbaH\x04*\x02 \x00H\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"\x14\n" +
	"\x12CreateChatResponse\"\xaa\x02\n" +
	"\x11UpdateChatRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b对话ID\xbaH\x04*\x02 \x00R\x02id\x12D\n" +
	"\x04chat\x18\x02 \x01(\v2\x13.ai.service.v1.ChatB\x1b\xe0A\x02\xbaG\x0f\x92\x02\f对话信息\xbaH\x03\xc8\x01\x01R\x04chat\x12>\n" +
	"\voperator_id\x18\x03 \x01(\rB\x18\xbaG\x0e\x92\x02\v操作人ID\xbaH\x04*\x02 \x00H\x00R\n" +
	"operatorId\x88\x01\x01\x12X\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskB\x1b\xe0A\x02\xbaG\x15\x92\x02\x12更新字段掩码R\n" +
	"updateMaskB\x0e\n" +
	"\f_operator_id\"\x14\n" +
	"\x12UpdateChatResponse\"\x8a\x01\n" +
	"\x11DeleteChatRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b对话ID\xbaH\x04*\x02 \x00R\x02id\x12>\n" +
	"\voperator_id\x18\x02 \x01(\rB\x18\xbaG\x0e\x92\x02\v操作人ID\xbaH\x04*\x02 \x00H\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"\x14\n" +
	"\x12DeleteChatResponse\"7\n" +
	"\x0eGetChatRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b对话ID\xbaH\x04*\x02 \x00R\x02id\":\n" +
	"\x0fGetChatResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.ai.service.v1.ChatR\x04chat\"\xec\x03\n" +
	"\x10ListChatsRequest\x12A\n" +
	"\tpage_size\x18\x01 \x01(\x05B$\xbaG!\x8a\x02\t\t\x00\x00\x00\x00\x00\x004@\x92\x02\x12每一页的行数R\bpageSize\x12=\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x1e\xbaG\x1b\x8a\x02\t\t\x00\x00\x00\x00\x00\x00\xf0?\x92\x02\f当前页码R\tpageToken\x127\n" +
	"\tno_paging\x18\x03 \x01(\bB\x15\xbaG\x12\x92\x02\x0f是否不分页H\x00R\bnopaging\x88\x01\x01\x12\\\n" +
	"\x06status\x18\x06 \x01(\x0e2\f.enum.StatusB1\xbaG$\x92\x02!状态 0 未知 1 启用 2 禁用\xbaH\a\x82\x01\x04\x10\x01 \x00H\x01R\x06status\x88\x01\x01\x12/\n" +
	"\x06filter\x18\n" +
	" \x01(\tB\x12\xbaG\x0f\x92\x02\f筛选条件H\x02R\x06filter\x88\x01\x01\x122\n" +
	"\border_by\x18\v \x01(\tB\x12\xbaG\x0f\x92\x02\f排序字段H\x03R\aorderBy\x88\x01\x01\x12)\n" +
	"\x04skip\x18\f \x01(\x05B\x15\xbaG\x12\x92\x02\x0f跳过的行数R\x04skipB\f\n" +
	"\n" +
	"_no_pagingB\t\n" +
	"\a_statusB\t\n" +
	"\a_filterB\v\n" +
	"\t_order_by\"|\n" +
	"\x11ListChatsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.ai.service.v1.ChatR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xfb\x01\n" +
	"\x19UpdateChatByStatusRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b对话ID\xbaH\x04*\x02 \x00R\x02id\x12\\\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.enum.StatusB1\xbaG$\x92\x02!状态 0 未知 1 启用 2 禁用\xbaH\a\x82\x01\x04\x10\x01 \x00H\x00R\x06status\x88\x01\x01\x12>\n" +
	"\voperator_id\x18\x03 \x01(\rB\x18\xbaG\x0e\x92\x02\v操作人ID\xbaH\x04*\x02 \x00H\x01R\n" +
	"operatorId\x88\x01\x01B\t\n" +
	"\a_statusB\x0e\n" +
	"\f_operator_id\"\x1c\n" +
	"\x1aUpdateChatByStatusResponse\"x\n" +
	"\x11StreamChatRequest\x12.\n" +
	"\achat_id\x18\x01 \x01(\rB\x15\xbaG\v\x92\x02\b对话ID\xbaH\x04*\x02 \x00R\x06chatId\x123\n" +
	"\amessage\x18\x02 \x01(\tB\x19\xbaG\x0f\x92\x02\f消息内容\xbaH\x04r\x02\x10\x01R\amessage\">\n" +
	"\x12StreamChatResponse\x12(\n" +
	"\tstream_id\x18\x01 \x01(\tB\v\xbaG\b\x92\x02\x05流IDR\bstreamId2\xab\f\n" +
	"\vChatService\x12\xd1\x01\n" +
	"\x0fListChatsSimple\x12\x1f.ai.service.v1.ListChatsRequest\x1a .ai.service.v1.ListChatsResponse\"{\xbaGZ\n" +
	"\x12对话管理服务\x12\x18获取对话简单列表\x1a\x18获取对话简单列表Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/ai/v1/ai/chats/simple\x12\xc4\x01\n" +
	"\tListChats\x12\x1f.ai.service.v1.ListChatsRequest\x1a .ai.service.v1.ListChatsResponse\"t\xbaGZ\n" +
	"\x12对话管理服务\x12\x18获取对话列表分页\x1a\x18获取对话列表分页Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x11\x12\x0f/ai/v1/ai/chats\x12\xac\x01\n" +
	"\aGetChat\x12\x1d.ai.service.v1.GetChatRequest\x1a\x13.ai.service.v1.Chat\"m\xbaGN\n" +
	"\x12对话管理服务\x12\x12获取对话数据\x1a\x12获取对话数据Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16\x12\x14/ai/v1/ai/chats/{id}\x12\xb5\x01\n" +
	"\n" +
	"CreateChat\x12 .ai.service.v1.CreateChatRequest\x1a!.ai.service.v1.CreateChatResponse\"b\xbaGB\n" +
	"\x12对话管理服务\x12\f创建对话\x1a\f创建对话Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x17:\x04chat\"\x0f/ai/v1/ai/chats\x12\xba\x01\n" +
	"\n" +
	"UpdateChat\x12 .ai.service.v1.UpdateChatRequest\x1a!.ai.service.v1.UpdateChatResponse\"g\xbaGB\n" +
	"\x12对话管理服务\x12\f更新对话\x1a\f更新对话Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1c:\x04chat\x1a\x14/ai/v1/ai/chats/{id}\x12\xb4\x01\n" +
	"\n" +
	"DeleteChat\x12 .ai.service.v1.DeleteChatRequest\x1a!.ai.service.v1.DeleteChatResponse\"a\xbaGB\n" +
	"\x12对话管理服务\x12\f删除对话\x1a\f删除对话Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16*\x14/ai/v1/ai/chats/{id}\x12\xe9\x01\n" +
	"\x12UpdateChatByStatus\x12(.ai.service.v1.UpdateChatByStatusRequest\x1a).ai.service.v1.UpdateChatByStatusResponse\"~\xbaGN\n" +
	"\x12对话管理服务\x12\x12更新对话状态\x1a\x12更新对话状态Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02':\x01*\x1a\"/ai/v1/ai/chats/status-update/{id}\x12\xb9\x01\n" +
	"\n" +
	"StreamChat\x12 .ai.service.v1.StreamChatRequest\x1a!.ai.service.v1.StreamChatResponse\"f\xbaGB\n" +
	"\x12对话管理服务\x12\f流式对话\x1a\f流式对话Z\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/ai/v1/ai/chats/streamB\x9b\x01\n" +
	"\x11com.ai.service.v1B\n" +
	"IChatProtoP\x01Z$backend-service/api/ai/service/v1;v1\xa2\x02\x03ASX\xaa\x02\rAi.Service.V1\xca\x02\rAi\\Service\\V1\xe2\x02\x19Ai\\Service\\V1\\GPBMetadata\xea\x02\x0fAi::Service::V1b\x06proto3"

var (
	file_ai_service_v1_i_chat_proto_rawDescOnce sync.Once
	file_ai_service_v1_i_chat_proto_rawDescData []byte
)

func file_ai_service_v1_i_chat_proto_rawDescGZIP() []byte {
	file_ai_service_v1_i_chat_proto_rawDescOnce.Do(func() {
		file_ai_service_v1_i_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_v1_i_chat_proto_rawDesc), len(file_ai_service_v1_i_chat_proto_rawDesc)))
	})
	return file_ai_service_v1_i_chat_proto_rawDescData
}

var file_ai_service_v1_i_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ai_service_v1_i_chat_proto_goTypes = []any{
	(*Chat)(nil),                       // 0: ai.service.v1.Chat
	(*CreateChatRequest)(nil),          // 1: ai.service.v1.CreateChatRequest
	(*CreateChatResponse)(nil),         // 2: ai.service.v1.CreateChatResponse
	(*UpdateChatRequest)(nil),          // 3: ai.service.v1.UpdateChatRequest
	(*UpdateChatResponse)(nil),         // 4: ai.service.v1.UpdateChatResponse
	(*DeleteChatRequest)(nil),          // 5: ai.service.v1.DeleteChatRequest
	(*DeleteChatResponse)(nil),         // 6: ai.service.v1.DeleteChatResponse
	(*GetChatRequest)(nil),             // 7: ai.service.v1.GetChatRequest
	(*GetChatResponse)(nil),            // 8: ai.service.v1.GetChatResponse
	(*ListChatsRequest)(nil),           // 9: ai.service.v1.ListChatsRequest
	(*ListChatsResponse)(nil),          // 10: ai.service.v1.ListChatsResponse
	(*UpdateChatByStatusRequest)(nil),  // 11: ai.service.v1.UpdateChatByStatusRequest
	(*UpdateChatByStatusResponse)(nil), // 12: ai.service.v1.UpdateChatByStatusResponse
	(*StreamChatRequest)(nil),          // 13: ai.service.v1.StreamChatRequest
	(*StreamChatResponse)(nil),         // 14: ai.service.v1.StreamChatResponse
	(enum.Status)(0),                   // 15: enum.Status
	(*fieldmaskpb.FieldMask)(nil),      // 16: google.protobuf.FieldMask
}
var file_ai_service_v1_i_chat_proto_depIdxs = []int32{
	15, // 0: ai.service.v1.Chat.status:type_name -> enum.Status
	0,  // 1: ai.service.v1.CreateChatRequest.chat:type_name -> ai.service.v1.Chat
	0,  // 2: ai.service.v1.UpdateChatRequest.chat:type_name -> ai.service.v1.Chat
	16, // 3: ai.service.v1.UpdateChatRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 4: ai.service.v1.GetChatResponse.chat:type_name -> ai.service.v1.Chat
	15, // 5: ai.service.v1.ListChatsRequest.status:type_name -> enum.Status
	0,  // 6: ai.service.v1.ListChatsResponse.items:type_name -> ai.service.v1.Chat
	15, // 7: ai.service.v1.UpdateChatByStatusRequest.status:type_name -> enum.Status
	9,  // 8: ai.service.v1.ChatService.ListChatsSimple:input_type -> ai.service.v1.ListChatsRequest
	9,  // 9: ai.service.v1.ChatService.ListChats:input_type -> ai.service.v1.ListChatsRequest
	7,  // 10: ai.service.v1.ChatService.GetChat:input_type -> ai.service.v1.GetChatRequest
	1,  // 11: ai.service.v1.ChatService.CreateChat:input_type -> ai.service.v1.CreateChatRequest
	3,  // 12: ai.service.v1.ChatService.UpdateChat:input_type -> ai.service.v1.UpdateChatRequest
	5,  // 13: ai.service.v1.ChatService.DeleteChat:input_type -> ai.service.v1.DeleteChatRequest
	11, // 14: ai.service.v1.ChatService.UpdateChatByStatus:input_type -> ai.service.v1.UpdateChatByStatusRequest
	13, // 15: ai.service.v1.ChatService.StreamChat:input_type -> ai.service.v1.StreamChatRequest
	10, // 16: ai.service.v1.ChatService.ListChatsSimple:output_type -> ai.service.v1.ListChatsResponse
	10, // 17: ai.service.v1.ChatService.ListChats:output_type -> ai.service.v1.ListChatsResponse
	0,  // 18: ai.service.v1.ChatService.GetChat:output_type -> ai.service.v1.Chat
	2,  // 19: ai.service.v1.ChatService.CreateChat:output_type -> ai.service.v1.CreateChatResponse
	4,  // 20: ai.service.v1.ChatService.UpdateChat:output_type -> ai.service.v1.UpdateChatResponse
	6,  // 21: ai.service.v1.ChatService.DeleteChat:output_type -> ai.service.v1.DeleteChatResponse
	12, // 22: ai.service.v1.ChatService.UpdateChatByStatus:output_type -> ai.service.v1.UpdateChatByStatusResponse
	14, // 23: ai.service.v1.ChatService.StreamChat:output_type -> ai.service.v1.StreamChatResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ai_service_v1_i_chat_proto_init() }
func file_ai_service_v1_i_chat_proto_init() {
	if File_ai_service_v1_i_chat_proto != nil {
		return
	}
	file_ai_service_v1_i_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_ai_service_v1_i_chat_proto_msgTypes[1].OneofWrappers = []any{}
	file_ai_service_v1_i_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_ai_service_v1_i_chat_proto_msgTypes[5].OneofWrappers = []any{}
	file_ai_service_v1_i_chat_proto_msgTypes[9].OneofWrappers = []any{}
	file_ai_service_v1_i_chat_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_v1_i_chat_proto_rawDesc), len(file_ai_service_v1_i_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_v1_i_chat_proto_goTypes,
		DependencyIndexes: file_ai_service_v1_i_chat_proto_depIdxs,
		MessageInfos:      file_ai_service_v1_i_chat_proto_msgTypes,
	}.Build()
	File_ai_service_v1_i_chat_proto = out.File
	file_ai_service_v1_i_chat_proto_goTypes = nil
	file_ai_service_v1_i_chat_proto_depIdxs = nil
}
