// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/admin/v1/i_dictionary.proto

package v1

import (
	v1 "backend-service/api/core/service/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_platform_admin_v1_i_dictionary_proto protoreflect.FileDescriptor

const file_platform_admin_v1_i_dictionary_proto_rawDesc = "" +
	"\n" +
	"$platform/admin/v1/i_dictionary.proto\x12\x11platform.admin.v1\x1a core/service/v1/dictionary.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xa6\n" +
	"\n" +
	"\x11DictionaryService\x12\x90\x01\n" +
	"\x13ListDictionaryTypes\x12+.core.service.v1.ListDictionaryTypesRequest\x1a,.core.service.v1.ListDictionaryTypesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/admin/v1/dictionaries\x12\x84\x01\n" +
	"\x11GetDictionaryType\x12).core.service.v1.GetDictionaryTypeRequest\x1a\x1f.core.service.v1.DictionaryType\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/admin/v1/dictionaries/{id}\x12\x91\x01\n" +
	"\x14CreateDictionaryType\x12,.core.service.v1.CreateDictionaryTypeRequest\x1a\x1f.core.service.v1.DictionaryType\"*\x82\xd3\xe4\x93\x02$:\n" +
	"dictionary\"\x16/admin/v1/dictionaries\x12\x96\x01\n" +
	"\x14UpdateDictionaryType\x12,.core.service.v1.UpdateDictionaryTypeRequest\x1a\x1f.core.service.v1.DictionaryType\"/\x82\xd3\xe4\x93\x02):\n" +
	"dictionary\x1a\x1b/admin/v1/dictionaries/{id}\x12\x81\x01\n" +
	"\x14DeleteDictionaryType\x12,.core.service.v1.DeleteDictionaryTypeRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/admin/v1/dictionaries/{id}\x12\x94\x01\n" +
	"\x13ListDictionaryItems\x12+.core.service.v1.ListDictionaryItemsRequest\x1a,.core.service.v1.ListDictionaryItemsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/admin/v1/dictionary-items\x12\x8f\x01\n" +
	"\x14CreateDictionaryItem\x12,.core.service.v1.CreateDictionaryItemRequest\x1a\x1f.core.service.v1.DictionaryItem\"(\x82\xd3\xe4\x93\x02\":\x04item\"\x1a/admin/v1/dictionary-items\x12\x94\x01\n" +
	"\x14UpdateDictionaryItem\x12,.core.service.v1.UpdateDictionaryItemRequest\x1a\x1f.core.service.v1.DictionaryItem\"-\x82\xd3\xe4\x93\x02':\x04item\x1a\x1f/admin/v1/dictionary-items/{id}\x12\x85\x01\n" +
	"\x14DeleteDictionaryItem\x12,.core.service.v1.DeleteDictionaryItemRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/admin/v1/dictionary-items/{id}B\xb9\x01\n" +
	"\x15com.platform.admin.v1B\x10IDictionaryProtoP\x01Z(backend-service/api/platform/admin/v1;v1\xa2\x02\x03PAX\xaa\x02\x11Platform.Admin.V1\xca\x02\x11Platform\\Admin\\V1\xe2\x02\x1dPlatform\\Admin\\V1\\GPBMetadata\xea\x02\x13Platform::Admin::V1b\x06proto3"

var file_platform_admin_v1_i_dictionary_proto_goTypes = []any{
	(*v1.ListDictionaryTypesRequest)(nil),  // 0: core.service.v1.ListDictionaryTypesRequest
	(*v1.GetDictionaryTypeRequest)(nil),    // 1: core.service.v1.GetDictionaryTypeRequest
	(*v1.CreateDictionaryTypeRequest)(nil), // 2: core.service.v1.CreateDictionaryTypeRequest
	(*v1.UpdateDictionaryTypeRequest)(nil), // 3: core.service.v1.UpdateDictionaryTypeRequest
	(*v1.DeleteDictionaryTypeRequest)(nil), // 4: core.service.v1.DeleteDictionaryTypeRequest
	(*v1.ListDictionaryItemsRequest)(nil),  // 5: core.service.v1.ListDictionaryItemsRequest
	(*v1.CreateDictionaryItemRequest)(nil), // 6: core.service.v1.CreateDictionaryItemRequest
	(*v1.UpdateDictionaryItemRequest)(nil), // 7: core.service.v1.UpdateDictionaryItemRequest
	(*v1.DeleteDictionaryItemRequest)(nil), // 8: core.service.v1.DeleteDictionaryItemRequest
	(*v1.ListDictionaryTypesResponse)(nil), // 9: core.service.v1.ListDictionaryTypesResponse
	(*v1.DictionaryType)(nil),              // 10: core.service.v1.DictionaryType
	(*emptypb.Empty)(nil),                  // 11: google.protobuf.Empty
	(*v1.ListDictionaryItemsResponse)(nil), // 12: core.service.v1.ListDictionaryItemsResponse
	(*v1.DictionaryItem)(nil),              // 13: core.service.v1.DictionaryItem
}
var file_platform_admin_v1_i_dictionary_proto_depIdxs = []int32{
	0,  // 0: platform.admin.v1.DictionaryService.ListDictionaryTypes:input_type -> core.service.v1.ListDictionaryTypesRequest
	1,  // 1: platform.admin.v1.DictionaryService.GetDictionaryType:input_type -> core.service.v1.GetDictionaryTypeRequest
	2,  // 2: platform.admin.v1.DictionaryService.CreateDictionaryType:input_type -> core.service.v1.CreateDictionaryTypeRequest
	3,  // 3: platform.admin.v1.DictionaryService.UpdateDictionaryType:input_type -> core.service.v1.UpdateDictionaryTypeRequest
	4,  // 4: platform.admin.v1.DictionaryService.DeleteDictionaryType:input_type -> core.service.v1.DeleteDictionaryTypeRequest
	5,  // 5: platform.admin.v1.DictionaryService.ListDictionaryItems:input_type -> core.service.v1.ListDictionaryItemsRequest
	6,  // 6: platform.admin.v1.DictionaryService.CreateDictionaryItem:input_type -> core.service.v1.CreateDictionaryItemRequest
	7,  // 7: platform.admin.v1.DictionaryService.UpdateDictionaryItem:input_type -> core.service.v1.UpdateDictionaryItemRequest
	8,  // 8: platform.admin.v1.DictionaryService.DeleteDictionaryItem:input_type -> core.service.v1.DeleteDictionaryItemRequest
	9,  // 9: platform.admin.v1.DictionaryService.ListDictionaryTypes:output_type -> core.service.v1.ListDictionaryTypesResponse
	10, // 10: platform.admin.v1.DictionaryService.GetDictionaryType:output_type -> core.service.v1.DictionaryType
	10, // 11: platform.admin.v1.DictionaryService.CreateDictionaryType:output_type -> core.service.v1.DictionaryType
	10, // 12: platform.admin.v1.DictionaryService.UpdateDictionaryType:output_type -> core.service.v1.DictionaryType
	11, // 13: platform.admin.v1.DictionaryService.DeleteDictionaryType:output_type -> google.protobuf.Empty
	12, // 14: platform.admin.v1.DictionaryService.ListDictionaryItems:output_type -> core.service.v1.ListDictionaryItemsResponse
	13, // 15: platform.admin.v1.DictionaryService.CreateDictionaryItem:output_type -> core.service.v1.DictionaryItem
	13, // 16: platform.admin.v1.DictionaryService.UpdateDictionaryItem:output_type -> core.service.v1.DictionaryItem
	11, // 17: platform.admin.v1.DictionaryService.DeleteDictionaryItem:output_type -> google.protobuf.Empty
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_platform_admin_v1_i_dictionary_proto_init() }
func file_platform_admin_v1_i_dictionary_proto_init() {
	if File_platform_admin_v1_i_dictionary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_admin_v1_i_dictionary_proto_rawDesc), len(file_platform_admin_v1_i_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_admin_v1_i_dictionary_proto_goTypes,
		DependencyIndexes: file_platform_admin_v1_i_dictionary_proto_depIdxs,
	}.Build()
	File_platform_admin_v1_i_dictionary_proto = out.File
	file_platform_admin_v1_i_dictionary_proto_goTypes = nil
	file_platform_admin_v1_i_dictionary_proto_depIdxs = nil
}
