// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: platform/admin/v1/i_file_center.proto

package v1

import (
	v1 "backend-service/api/core/service/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileCenterService_CreateFileUploadSession_FullMethodName = "/platform.admin.v1.FileCenterService/CreateFileUploadSession"
	FileCenterService_ConfirmFileUpload_FullMethodName       = "/platform.admin.v1.FileCenterService/ConfirmFileUpload"
	FileCenterService_GetFileObject_FullMethodName           = "/platform.admin.v1.FileCenterService/GetFileObject"
	FileCenterService_ListFileObjects_FullMethodName         = "/platform.admin.v1.FileCenterService/ListFileObjects"
	FileCenterService_PresignFileDownload_FullMethodName     = "/platform.admin.v1.FileCenterService/PresignFileDownload"
	FileCenterService_DeleteFileObject_FullMethodName        = "/platform.admin.v1.FileCenterService/DeleteFileObject"
)

// FileCenterServiceClient is the client API for FileCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileCenterServiceClient interface {
	CreateFileUploadSession(ctx context.Context, in *v1.CreateFileUploadSessionRequest, opts ...grpc.CallOption) (*v1.CreateFileUploadSessionResponse, error)
	ConfirmFileUpload(ctx context.Context, in *v1.ConfirmFileUploadRequest, opts ...grpc.CallOption) (*v1.ConfirmFileUploadResponse, error)
	GetFileObject(ctx context.Context, in *v1.GetFileObjectRequest, opts ...grpc.CallOption) (*v1.FileObject, error)
	ListFileObjects(ctx context.Context, in *v1.ListFileObjectsRequest, opts ...grpc.CallOption) (*v1.ListFileObjectsResponse, error)
	PresignFileDownload(ctx context.Context, in *v1.PresignFileDownloadRequest, opts ...grpc.CallOption) (*v1.PresignFileDownloadResponse, error)
	DeleteFileObject(ctx context.Context, in *v1.DeleteFileObjectRequest, opts ...grpc.CallOption) (*v1.DeleteFileObjectResponse, error)
}

type fileCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileCenterServiceClient(cc grpc.ClientConnInterface) FileCenterServiceClient {
	return &fileCenterServiceClient{cc}
}

func (c *fileCenterServiceClient) CreateFileUploadSession(ctx context.Context, in *v1.CreateFileUploadSessionRequest, opts ...grpc.CallOption) (*v1.CreateFileUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateFileUploadSessionResponse)
	err := c.cc.Invoke(ctx, FileCenterService_CreateFileUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileCenterServiceClient) ConfirmFileUpload(ctx context.Context, in *v1.ConfirmFileUploadRequest, opts ...grpc.CallOption) (*v1.ConfirmFileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ConfirmFileUploadResponse)
	err := c.cc.Invoke(ctx, FileCenterService_ConfirmFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileCenterServiceClient) GetFileObject(ctx context.Context, in *v1.GetFileObjectRequest, opts ...grpc.CallOption) (*v1.FileObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.FileObject)
	err := c.cc.Invoke(ctx, FileCenterService_GetFileObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileCenterServiceClient) ListFileObjects(ctx context.Context, in *v1.ListFileObjectsRequest, opts ...grpc.CallOption) (*v1.ListFileObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListFileObjectsResponse)
	err := c.cc.Invoke(ctx, FileCenterService_ListFileObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileCenterServiceClient) PresignFileDownload(ctx context.Context, in *v1.PresignFileDownloadRequest, opts ...grpc.CallOption) (*v1.PresignFileDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.PresignFileDownloadResponse)
	err := c.cc.Invoke(ctx, FileCenterService_PresignFileDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileCenterServiceClient) DeleteFileObject(ctx context.Context, in *v1.DeleteFileObjectRequest, opts ...grpc.CallOption) (*v1.DeleteFileObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteFileObjectResponse)
	err := c.cc.Invoke(ctx, FileCenterService_DeleteFileObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileCenterServiceServer is the server API for FileCenterService service.
// All implementations must embed UnimplementedFileCenterServiceServer
// for forward compatibility.
type FileCenterServiceServer interface {
	CreateFileUploadSession(context.Context, *v1.CreateFileUploadSessionRequest) (*v1.CreateFileUploadSessionResponse, error)
	ConfirmFileUpload(context.Context, *v1.ConfirmFileUploadRequest) (*v1.ConfirmFileUploadResponse, error)
	GetFileObject(context.Context, *v1.GetFileObjectRequest) (*v1.FileObject, error)
	ListFileObjects(context.Context, *v1.ListFileObjectsRequest) (*v1.ListFileObjectsResponse, error)
	PresignFileDownload(context.Context, *v1.PresignFileDownloadRequest) (*v1.PresignFileDownloadResponse, error)
	DeleteFileObject(context.Context, *v1.DeleteFileObjectRequest) (*v1.DeleteFileObjectResponse, error)
	mustEmbedUnimplementedFileCenterServiceServer()
}

// UnimplementedFileCenterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileCenterServiceServer struct{}

func (UnimplementedFileCenterServiceServer) CreateFileUploadSession(context.Context, *v1.CreateFileUploadSessionRequest) (*v1.CreateFileUploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFileUploadSession not implemented")
}
func (UnimplementedFileCenterServiceServer) ConfirmFileUpload(context.Context, *v1.ConfirmFileUploadRequest) (*v1.ConfirmFileUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmFileUpload not implemented")
}
func (UnimplementedFileCenterServiceServer) GetFileObject(context.Context, *v1.GetFileObjectRequest) (*v1.FileObject, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileObject not implemented")
}
func (UnimplementedFileCenterServiceServer) ListFileObjects(context.Context, *v1.ListFileObjectsRequest) (*v1.ListFileObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFileObjects not implemented")
}
func (UnimplementedFileCenterServiceServer) PresignFileDownload(context.Context, *v1.PresignFileDownloadRequest) (*v1.PresignFileDownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PresignFileDownload not implemented")
}
func (UnimplementedFileCenterServiceServer) DeleteFileObject(context.Context, *v1.DeleteFileObjectRequest) (*v1.DeleteFileObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFileObject not implemented")
}
func (UnimplementedFileCenterServiceServer) mustEmbedUnimplementedFileCenterServiceServer() {}
func (UnimplementedFileCenterServiceServer) testEmbeddedByValue()                           {}

// UnsafeFileCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileCenterServiceServer will
// result in compilation errors.
type UnsafeFileCenterServiceServer interface {
	mustEmbedUnimplementedFileCenterServiceServer()
}

func RegisterFileCenterServiceServer(s grpc.ServiceRegistrar, srv FileCenterServiceServer) {
	// If the following call panics, it indicates UnimplementedFileCenterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileCenterService_ServiceDesc, srv)
}

func _FileCenterService_CreateFileUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateFileUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).CreateFileUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_CreateFileUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).CreateFileUploadSession(ctx, req.(*v1.CreateFileUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileCenterService_ConfirmFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ConfirmFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).ConfirmFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_ConfirmFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).ConfirmFileUpload(ctx, req.(*v1.ConfirmFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileCenterService_GetFileObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetFileObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).GetFileObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_GetFileObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).GetFileObject(ctx, req.(*v1.GetFileObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileCenterService_ListFileObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListFileObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).ListFileObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_ListFileObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).ListFileObjects(ctx, req.(*v1.ListFileObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileCenterService_PresignFileDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PresignFileDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).PresignFileDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_PresignFileDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).PresignFileDownload(ctx, req.(*v1.PresignFileDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileCenterService_DeleteFileObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteFileObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCenterServiceServer).DeleteFileObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCenterService_DeleteFileObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCenterServiceServer).DeleteFileObject(ctx, req.(*v1.DeleteFileObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileCenterService_ServiceDesc is the grpc.ServiceDesc for FileCenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.admin.v1.FileCenterService",
	HandlerType: (*FileCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileUploadSession",
			Handler:    _FileCenterService_CreateFileUploadSession_Handler,
		},
		{
			MethodName: "ConfirmFileUpload",
			Handler:    _FileCenterService_ConfirmFileUpload_Handler,
		},
		{
			MethodName: "GetFileObject",
			Handler:    _FileCenterService_GetFileObject_Handler,
		},
		{
			MethodName: "ListFileObjects",
			Handler:    _FileCenterService_ListFileObjects_Handler,
		},
		{
			MethodName: "PresignFileDownload",
			Handler:    _FileCenterService_PresignFileDownload_Handler,
		},
		{
			MethodName: "DeleteFileObject",
			Handler:    _FileCenterService_DeleteFileObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/admin/v1/i_file_center.proto",
}
