// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: platform/admin/v1/i_menu.proto

package v1

import (
	v1 "backend-service/api/core/service/v1"
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMenuServiceCreateMenu = "/platform.admin.v1.MenuService/CreateMenu"
const OperationMenuServiceDeleteMenu = "/platform.admin.v1.MenuService/DeleteMenu"
const OperationMenuServiceExistMenuByName = "/platform.admin.v1.MenuService/ExistMenuByName"
const OperationMenuServiceExistMenuByPath = "/platform.admin.v1.MenuService/ExistMenuByPath"
const OperationMenuServiceGetMenu = "/platform.admin.v1.MenuService/GetMenu"
const OperationMenuServiceListMenus = "/platform.admin.v1.MenuService/ListMenus"
const OperationMenuServiceListMenusAll = "/platform.admin.v1.MenuService/ListMenusAll"
const OperationMenuServiceListMenusTree = "/platform.admin.v1.MenuService/ListMenusTree"
const OperationMenuServiceUpdateMenu = "/platform.admin.v1.MenuService/UpdateMenu"
const OperationMenuServiceUpdateMenuByStatus = "/platform.admin.v1.MenuService/UpdateMenuByStatus"

type MenuServiceHTTPServer interface {
	// CreateMenu 创建菜单
	CreateMenu(context.Context, *v1.CreateMenuRequest) (*v1.CreateMenuResponse, error)
	// DeleteMenu 删除菜单
	DeleteMenu(context.Context, *v1.DeleteMenuRequest) (*v1.DeleteMenuResponse, error)
	// ExistMenuByName 判断菜单名是否存在
	ExistMenuByName(context.Context, *v1.ExistMenuByNameRequest) (*v1.ExistMenuByNameResponse, error)
	// ExistMenuByPath 判断菜单路径是否存在
	ExistMenuByPath(context.Context, *v1.ExistMenuByPathRequest) (*v1.ExistMenuByPathResponse, error)
	// GetMenu 获取菜单数据
	GetMenu(context.Context, *v1.GetMenuRequest) (*v1.Menu, error)
	// ListMenus 获取菜单列表
	ListMenus(context.Context, *v1.ListMenusRequest) (*v1.ListMenusResponse, error)
	// ListMenusAll 获取所有菜单
	ListMenusAll(context.Context, *emptypb.Empty) (*v1.ListMenusResponse, error)
	// ListMenusTree 获取菜单树
	ListMenusTree(context.Context, *v1.ListMenusTreeRequest) (*v1.ListMenusTreeResponse, error)
	// UpdateMenu 更新菜单
	UpdateMenu(context.Context, *v1.UpdateMenuRequest) (*v1.UpdateMenuResponse, error)
	// UpdateMenuByStatus 更新菜单状态
	UpdateMenuByStatus(context.Context, *v1.UpdateMenuByStatusRequest) (*v1.UpdateMenuByStatusResponse, error)
}

func RegisterMenuServiceHTTPServer(s *http.Server, srv MenuServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/v1/menus/all", _MenuService_ListMenusAll0_HTTP_Handler(srv))
	r.GET("/admin/v1/menus/tree", _MenuService_ListMenusTree0_HTTP_Handler(srv))
	r.GET("/admin/v1/menus/tree/{parent_id}", _MenuService_ListMenusTree1_HTTP_Handler(srv))
	r.GET("/admin/v1/menus", _MenuService_ListMenus0_HTTP_Handler(srv))
	r.GET("/admin/v1/menus/{id}", _MenuService_GetMenu0_HTTP_Handler(srv))
	r.POST("/admin/v1/menus", _MenuService_CreateMenu0_HTTP_Handler(srv))
	r.PUT("/admin/v1/menus/{id}", _MenuService_UpdateMenu0_HTTP_Handler(srv))
	r.DELETE("/admin/v1/menus/{id}", _MenuService_DeleteMenu0_HTTP_Handler(srv))
	r.POST("/admin/v1/menus/path-exists", _MenuService_ExistMenuByPath0_HTTP_Handler(srv))
	r.GET("/admin/v1/menus/path-exists/{id}", _MenuService_ExistMenuByPath1_HTTP_Handler(srv))
	r.POST("/admin/v1/menus/name-exists", _MenuService_ExistMenuByName0_HTTP_Handler(srv))
	r.GET("/admin/v1/menus/name-exists/{id}", _MenuService_ExistMenuByName1_HTTP_Handler(srv))
	r.POST("/admin/v1/menus/{id}:status-update", _MenuService_UpdateMenuByStatus0_HTTP_Handler(srv))
}

func _MenuService_ListMenusAll0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceListMenusAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMenusAll(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListMenusResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ListMenusTree0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListMenusTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceListMenusTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMenusTree(ctx, req.(*v1.ListMenusTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListMenusTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ListMenusTree1_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListMenusTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceListMenusTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMenusTree(ctx, req.(*v1.ListMenusTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListMenusTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ListMenus0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListMenusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceListMenus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMenus(ctx, req.(*v1.ListMenusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListMenusResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_GetMenu0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.GetMenuRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceGetMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMenu(ctx, req.(*v1.GetMenuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Menu)
		return ctx.Result(200, reply)
	}
}

func _MenuService_CreateMenu0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.CreateMenuRequest
		if err := ctx.Bind(&in.Menu); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceCreateMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMenu(ctx, req.(*v1.CreateMenuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.CreateMenuResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_UpdateMenu0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.UpdateMenuRequest
		if err := ctx.Bind(&in.Menu); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceUpdateMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMenu(ctx, req.(*v1.UpdateMenuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.UpdateMenuResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_DeleteMenu0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.DeleteMenuRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceDeleteMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMenu(ctx, req.(*v1.DeleteMenuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.DeleteMenuResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ExistMenuByPath0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ExistMenuByPathRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceExistMenuByPath)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExistMenuByPath(ctx, req.(*v1.ExistMenuByPathRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ExistMenuByPathResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ExistMenuByPath1_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ExistMenuByPathRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceExistMenuByPath)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExistMenuByPath(ctx, req.(*v1.ExistMenuByPathRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ExistMenuByPathResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ExistMenuByName0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ExistMenuByNameRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceExistMenuByName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExistMenuByName(ctx, req.(*v1.ExistMenuByNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ExistMenuByNameResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_ExistMenuByName1_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ExistMenuByNameRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceExistMenuByName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExistMenuByName(ctx, req.(*v1.ExistMenuByNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ExistMenuByNameResponse)
		return ctx.Result(200, reply)
	}
}

func _MenuService_UpdateMenuByStatus0_HTTP_Handler(srv MenuServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.UpdateMenuByStatusRequest
		if err := ctx.Bind(&in.Status); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceUpdateMenuByStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMenuByStatus(ctx, req.(*v1.UpdateMenuByStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.UpdateMenuByStatusResponse)
		return ctx.Result(200, reply)
	}
}

type MenuServiceHTTPClient interface {
	// CreateMenu 创建菜单
	CreateMenu(ctx context.Context, req *v1.CreateMenuRequest, opts ...http.CallOption) (rsp *v1.CreateMenuResponse, err error)
	// DeleteMenu 删除菜单
	DeleteMenu(ctx context.Context, req *v1.DeleteMenuRequest, opts ...http.CallOption) (rsp *v1.DeleteMenuResponse, err error)
	// ExistMenuByName 判断菜单名是否存在
	ExistMenuByName(ctx context.Context, req *v1.ExistMenuByNameRequest, opts ...http.CallOption) (rsp *v1.ExistMenuByNameResponse, err error)
	// ExistMenuByPath 判断菜单路径是否存在
	ExistMenuByPath(ctx context.Context, req *v1.ExistMenuByPathRequest, opts ...http.CallOption) (rsp *v1.ExistMenuByPathResponse, err error)
	// GetMenu 获取菜单数据
	GetMenu(ctx context.Context, req *v1.GetMenuRequest, opts ...http.CallOption) (rsp *v1.Menu, err error)
	// ListMenus 获取菜单列表
	ListMenus(ctx context.Context, req *v1.ListMenusRequest, opts ...http.CallOption) (rsp *v1.ListMenusResponse, err error)
	// ListMenusAll 获取所有菜单
	ListMenusAll(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *v1.ListMenusResponse, err error)
	// ListMenusTree 获取菜单树
	ListMenusTree(ctx context.Context, req *v1.ListMenusTreeRequest, opts ...http.CallOption) (rsp *v1.ListMenusTreeResponse, err error)
	// UpdateMenu 更新菜单
	UpdateMenu(ctx context.Context, req *v1.UpdateMenuRequest, opts ...http.CallOption) (rsp *v1.UpdateMenuResponse, err error)
	// UpdateMenuByStatus 更新菜单状态
	UpdateMenuByStatus(ctx context.Context, req *v1.UpdateMenuByStatusRequest, opts ...http.CallOption) (rsp *v1.UpdateMenuByStatusResponse, err error)
}

type MenuServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMenuServiceHTTPClient(client *http.Client) MenuServiceHTTPClient {
	return &MenuServiceHTTPClientImpl{client}
}

// CreateMenu 创建菜单
func (c *MenuServiceHTTPClientImpl) CreateMenu(ctx context.Context, in *v1.CreateMenuRequest, opts ...http.CallOption) (*v1.CreateMenuResponse, error) {
	var out v1.CreateMenuResponse
	pattern := "/admin/v1/menus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuServiceCreateMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Menu, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteMenu 删除菜单
func (c *MenuServiceHTTPClientImpl) DeleteMenu(ctx context.Context, in *v1.DeleteMenuRequest, opts ...http.CallOption) (*v1.DeleteMenuResponse, error) {
	var out v1.DeleteMenuResponse
	pattern := "/admin/v1/menus/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceDeleteMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExistMenuByName 判断菜单名是否存在
func (c *MenuServiceHTTPClientImpl) ExistMenuByName(ctx context.Context, in *v1.ExistMenuByNameRequest, opts ...http.CallOption) (*v1.ExistMenuByNameResponse, error) {
	var out v1.ExistMenuByNameResponse
	pattern := "/admin/v1/menus/name-exists/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceExistMenuByName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExistMenuByPath 判断菜单路径是否存在
func (c *MenuServiceHTTPClientImpl) ExistMenuByPath(ctx context.Context, in *v1.ExistMenuByPathRequest, opts ...http.CallOption) (*v1.ExistMenuByPathResponse, error) {
	var out v1.ExistMenuByPathResponse
	pattern := "/admin/v1/menus/path-exists/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceExistMenuByPath))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMenu 获取菜单数据
func (c *MenuServiceHTTPClientImpl) GetMenu(ctx context.Context, in *v1.GetMenuRequest, opts ...http.CallOption) (*v1.Menu, error) {
	var out v1.Menu
	pattern := "/admin/v1/menus/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceGetMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMenus 获取菜单列表
func (c *MenuServiceHTTPClientImpl) ListMenus(ctx context.Context, in *v1.ListMenusRequest, opts ...http.CallOption) (*v1.ListMenusResponse, error) {
	var out v1.ListMenusResponse
	pattern := "/admin/v1/menus"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceListMenus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMenusAll 获取所有菜单
func (c *MenuServiceHTTPClientImpl) ListMenusAll(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*v1.ListMenusResponse, error) {
	var out v1.ListMenusResponse
	pattern := "/admin/v1/menus/all"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceListMenusAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMenusTree 获取菜单树
func (c *MenuServiceHTTPClientImpl) ListMenusTree(ctx context.Context, in *v1.ListMenusTreeRequest, opts ...http.CallOption) (*v1.ListMenusTreeResponse, error) {
	var out v1.ListMenusTreeResponse
	pattern := "/admin/v1/menus/tree/{parent_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuServiceListMenusTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMenu 更新菜单
func (c *MenuServiceHTTPClientImpl) UpdateMenu(ctx context.Context, in *v1.UpdateMenuRequest, opts ...http.CallOption) (*v1.UpdateMenuResponse, error) {
	var out v1.UpdateMenuResponse
	pattern := "/admin/v1/menus/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuServiceUpdateMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Menu, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMenuByStatus 更新菜单状态
func (c *MenuServiceHTTPClientImpl) UpdateMenuByStatus(ctx context.Context, in *v1.UpdateMenuByStatusRequest, opts ...http.CallOption) (*v1.UpdateMenuByStatusResponse, error) {
	var out v1.UpdateMenuByStatusResponse
	pattern := "/admin/v1/menus/{id}:status-update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuServiceUpdateMenuByStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Status, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
