// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: platform/admin/v1/i_webhook.proto

package v1

import (
	v1 "backend-service/api/core/service/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookService_ListWebhookSubscriptions_FullMethodName  = "/platform.admin.v1.WebhookService/ListWebhookSubscriptions"
	WebhookService_GetWebhookSubscription_FullMethodName    = "/platform.admin.v1.WebhookService/GetWebhookSubscription"
	WebhookService_CreateWebhookSubscription_FullMethodName = "/platform.admin.v1.WebhookService/CreateWebhookSubscription"
	WebhookService_UpdateWebhookSubscription_FullMethodName = "/platform.admin.v1.WebhookService/UpdateWebhookSubscription"
	WebhookService_DeleteWebhookSubscription_FullMethodName = "/platform.admin.v1.WebhookService/DeleteWebhookSubscription"
	WebhookService_ListWebhookDeliveryLogs_FullMethodName   = "/platform.admin.v1.WebhookService/ListWebhookDeliveryLogs"
	WebhookService_GetWebhookDeliveryLog_FullMethodName     = "/platform.admin.v1.WebhookService/GetWebhookDeliveryLog"
	WebhookService_RetryWebhookDelivery_FullMethodName      = "/platform.admin.v1.WebhookService/RetryWebhookDelivery"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookServiceClient interface {
	// Subscription management
	ListWebhookSubscriptions(ctx context.Context, in *v1.ListWebhookSubscriptionsRequest, opts ...grpc.CallOption) (*v1.ListWebhookSubscriptionsResponse, error)
	GetWebhookSubscription(ctx context.Context, in *v1.GetWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error)
	CreateWebhookSubscription(ctx context.Context, in *v1.CreateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error)
	UpdateWebhookSubscription(ctx context.Context, in *v1.UpdateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error)
	DeleteWebhookSubscription(ctx context.Context, in *v1.DeleteWebhookSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delivery log management
	ListWebhookDeliveryLogs(ctx context.Context, in *v1.ListWebhookDeliveryLogsRequest, opts ...grpc.CallOption) (*v1.ListWebhookDeliveryLogsResponse, error)
	GetWebhookDeliveryLog(ctx context.Context, in *v1.GetWebhookDeliveryLogRequest, opts ...grpc.CallOption) (*v1.WebhookDeliveryLog, error)
	RetryWebhookDelivery(ctx context.Context, in *v1.RetryWebhookDeliveryRequest, opts ...grpc.CallOption) (*v1.RetryWebhookDeliveryResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) ListWebhookSubscriptions(ctx context.Context, in *v1.ListWebhookSubscriptionsRequest, opts ...grpc.CallOption) (*v1.ListWebhookSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListWebhookSubscriptionsResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhookSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookSubscription(ctx context.Context, in *v1.GetWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.WebhookSubscription)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) CreateWebhookSubscription(ctx context.Context, in *v1.CreateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.WebhookSubscription)
	err := c.cc.Invoke(ctx, WebhookService_CreateWebhookSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) UpdateWebhookSubscription(ctx context.Context, in *v1.UpdateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*v1.WebhookSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.WebhookSubscription)
	err := c.cc.Invoke(ctx, WebhookService_UpdateWebhookSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) DeleteWebhookSubscription(ctx context.Context, in *v1.DeleteWebhookSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WebhookService_DeleteWebhookSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListWebhookDeliveryLogs(ctx context.Context, in *v1.ListWebhookDeliveryLogsRequest, opts ...grpc.CallOption) (*v1.ListWebhookDeliveryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListWebhookDeliveryLogsResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhookDeliveryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookDeliveryLog(ctx context.Context, in *v1.GetWebhookDeliveryLogRequest, opts ...grpc.CallOption) (*v1.WebhookDeliveryLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.WebhookDeliveryLog)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookDeliveryLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) RetryWebhookDelivery(ctx context.Context, in *v1.RetryWebhookDeliveryRequest, opts ...grpc.CallOption) (*v1.RetryWebhookDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RetryWebhookDeliveryResponse)
	err := c.cc.Invoke(ctx, WebhookService_RetryWebhookDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility.
type WebhookServiceServer interface {
	// Subscription management
	ListWebhookSubscriptions(context.Context, *v1.ListWebhookSubscriptionsRequest) (*v1.ListWebhookSubscriptionsResponse, error)
	GetWebhookSubscription(context.Context, *v1.GetWebhookSubscriptionRequest) (*v1.WebhookSubscription, error)
	CreateWebhookSubscription(context.Context, *v1.CreateWebhookSubscriptionRequest) (*v1.WebhookSubscription, error)
	UpdateWebhookSubscription(context.Context, *v1.UpdateWebhookSubscriptionRequest) (*v1.WebhookSubscription, error)
	DeleteWebhookSubscription(context.Context, *v1.DeleteWebhookSubscriptionRequest) (*emptypb.Empty, error)
	// Delivery log management
	ListWebhookDeliveryLogs(context.Context, *v1.ListWebhookDeliveryLogsRequest) (*v1.ListWebhookDeliveryLogsResponse, error)
	GetWebhookDeliveryLog(context.Context, *v1.GetWebhookDeliveryLogRequest) (*v1.WebhookDeliveryLog, error)
	RetryWebhookDelivery(context.Context, *v1.RetryWebhookDeliveryRequest) (*v1.RetryWebhookDeliveryResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookServiceServer struct{}

func (UnimplementedWebhookServiceServer) ListWebhookSubscriptions(context.Context, *v1.ListWebhookSubscriptionsRequest) (*v1.ListWebhookSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhookSubscriptions not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookSubscription(context.Context, *v1.GetWebhookSubscriptionRequest) (*v1.WebhookSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) CreateWebhookSubscription(context.Context, *v1.CreateWebhookSubscriptionRequest) (*v1.WebhookSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) UpdateWebhookSubscription(context.Context, *v1.UpdateWebhookSubscriptionRequest) (*v1.WebhookSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) DeleteWebhookSubscription(context.Context, *v1.DeleteWebhookSubscriptionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) ListWebhookDeliveryLogs(context.Context, *v1.ListWebhookDeliveryLogsRequest) (*v1.ListWebhookDeliveryLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhookDeliveryLogs not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookDeliveryLog(context.Context, *v1.GetWebhookDeliveryLogRequest) (*v1.WebhookDeliveryLog, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookDeliveryLog not implemented")
}
func (UnimplementedWebhookServiceServer) RetryWebhookDelivery(context.Context, *v1.RetryWebhookDeliveryRequest) (*v1.RetryWebhookDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryWebhookDelivery not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}
func (UnimplementedWebhookServiceServer) testEmbeddedByValue()                        {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_ListWebhookSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListWebhookSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhookSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhookSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhookSubscriptions(ctx, req.(*v1.ListWebhookSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookSubscription(ctx, req.(*v1.GetWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_CreateWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).CreateWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_CreateWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).CreateWebhookSubscription(ctx, req.(*v1.CreateWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_UpdateWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).UpdateWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_UpdateWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).UpdateWebhookSubscription(ctx, req.(*v1.UpdateWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_DeleteWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).DeleteWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_DeleteWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).DeleteWebhookSubscription(ctx, req.(*v1.DeleteWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListWebhookDeliveryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListWebhookDeliveryLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhookDeliveryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhookDeliveryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhookDeliveryLogs(ctx, req.(*v1.ListWebhookDeliveryLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookDeliveryLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetWebhookDeliveryLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookDeliveryLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookDeliveryLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookDeliveryLog(ctx, req.(*v1.GetWebhookDeliveryLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_RetryWebhookDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RetryWebhookDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).RetryWebhookDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_RetryWebhookDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).RetryWebhookDelivery(ctx, req.(*v1.RetryWebhookDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.admin.v1.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWebhookSubscriptions",
			Handler:    _WebhookService_ListWebhookSubscriptions_Handler,
		},
		{
			MethodName: "GetWebhookSubscription",
			Handler:    _WebhookService_GetWebhookSubscription_Handler,
		},
		{
			MethodName: "CreateWebhookSubscription",
			Handler:    _WebhookService_CreateWebhookSubscription_Handler,
		},
		{
			MethodName: "UpdateWebhookSubscription",
			Handler:    _WebhookService_UpdateWebhookSubscription_Handler,
		},
		{
			MethodName: "DeleteWebhookSubscription",
			Handler:    _WebhookService_DeleteWebhookSubscription_Handler,
		},
		{
			MethodName: "ListWebhookDeliveryLogs",
			Handler:    _WebhookService_ListWebhookDeliveryLogs_Handler,
		},
		{
			MethodName: "GetWebhookDeliveryLog",
			Handler:    _WebhookService_GetWebhookDeliveryLog_Handler,
		},
		{
			MethodName: "RetryWebhookDelivery",
			Handler:    _WebhookService_RetryWebhookDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/admin/v1/i_webhook.proto",
}
