server:
  http:
    addr: 0.0.0.0:8110
    timeout: 30s
    corsAllowedOrigins: '*'
    rateLimitPerMinute: 0
  grpc:
    addr: 0.0.0.0:9110
    timeout: 30s
data:
  redis:
    network: tcp
    addr: 127.0.0.1:6379
    password: ''
    db: 14
    read_timeout: 0.2s
    write_timeout: 0.2s
    token_key_prefix: 'oauth2_access_token:'
qua:
  base_url: http://api.bdksim-pro.test.bedoke.com
  timeout: 10s
  forward_user_token: true
  endpoints:
    list_depts: /admin-api/system/dept/list
    list_users: /admin-api/qua/member-extended/page
    get_user: ''
    get_dept: ''
  page_size: 0
  extra_headers:
    tenant-id: ''
    zone: Asia/Shanghai
asr:
  default_batch_provider: funasr
  default_stream_provider: xunfei
  upload:
    audio_dir: ./upload/audio
    retention_days: 7
  timeouts:
    recognize: 30s
    stream: 60s
  providers:
    funasr:
      enabled: true
      addr: http://127.0.0.1:18000
      stream_addr: ''
      sample_rate: 16000
      language: zh
    xunfei:
      enabled: true
      host: iat-api.xfyun.cn
      uri: /v2/iat
      app_id: 2d8c3dd7
      api_key: 641cdc25afd21421685c6ec2ce24149c
      api_secret: MWEyMzg2ODhiMThhY2E2MWJmZWQ4YjQ4
      sample_rate: 16000
    whisper:
      enabled: false
    aliyun:
      enabled: false
enhancement:
  pipeline:
  - cleaning
  - filler
  - vocab_matching
  - alias_resolution
  - deterministic_replacement
  - pinyin_correction
  - fuzzy_matching
  - context_correction
  pinyin_threshold: 0.85
  fuzzy_auto_threshold: 0.8
  fuzzy_suggest_threshold: 0.6
  llm_enabled: false
  timeout: 2s
tenant_vocab:
  sync_interval: 300s
  initial_warmup: true
  concurrency: 4
  include_departments: true
  include_user_nickname: true
  include_user_realname: true
  custom_alias_field: alias
system_dict:
  path: ./configs/dictionaries/system.json
  hot_reload: true
tenant_registry:
  path: ./configs/tenants.json
vocab_rules:
  sources:
    qua:
      entity_mappings:
      - match:
          entity_type: user
        emit:
          standard_text: name
          category: PERSON
          aliases:
          - mobile
          pinyin_hint: name
          priority: '50'
          include_when: status==1 AND name!~测试 AND name!~入职 AND name!~账号 AND name!~权限
            AND name!~成员 AND name!~动态 AND name!~员工 AND name!~管理 AND name!~张三 AND name!~小子
            AND name!~可可 AND name!~新人 AND name!~花花
      - match:
          entity_type: department
        emit:
          standard_text: name
          category: ORGANIZATION
          pinyin_hint: name
          priority: '30'
