// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: platform/service/v1/notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotificationServiceCountMyUnreadNotifications = "/platform.service.v1.NotificationService/CountMyUnreadNotifications"
const OperationNotificationServiceCreateNotificationTemplate = "/platform.service.v1.NotificationService/CreateNotificationTemplate"
const OperationNotificationServiceDeleteNotificationTemplate = "/platform.service.v1.NotificationService/DeleteNotificationTemplate"
const OperationNotificationServiceGetNotificationMessage = "/platform.service.v1.NotificationService/GetNotificationMessage"
const OperationNotificationServiceGetNotificationTemplate = "/platform.service.v1.NotificationService/GetNotificationTemplate"
const OperationNotificationServiceListMyNotifications = "/platform.service.v1.NotificationService/ListMyNotifications"
const OperationNotificationServiceListNotificationMessages = "/platform.service.v1.NotificationService/ListNotificationMessages"
const OperationNotificationServiceListNotificationTemplates = "/platform.service.v1.NotificationService/ListNotificationTemplates"
const OperationNotificationServiceMarkNotificationRead = "/platform.service.v1.NotificationService/MarkNotificationRead"
const OperationNotificationServiceMarkNotificationsRead = "/platform.service.v1.NotificationService/MarkNotificationsRead"
const OperationNotificationServiceSendInAppNotification = "/platform.service.v1.NotificationService/SendInAppNotification"
const OperationNotificationServiceSendNotification = "/platform.service.v1.NotificationService/SendNotification"
const OperationNotificationServiceUpdateNotificationTemplate = "/platform.service.v1.NotificationService/UpdateNotificationTemplate"

type NotificationServiceHTTPServer interface {
	CountMyUnreadNotifications(context.Context, *CountMyUnreadNotificationsRequest) (*CountMyUnreadNotificationsResponse, error)
	CreateNotificationTemplate(context.Context, *CreateNotificationTemplateRequest) (*NotificationTemplate, error)
	DeleteNotificationTemplate(context.Context, *DeleteNotificationTemplateRequest) (*emptypb.Empty, error)
	GetNotificationMessage(context.Context, *GetNotificationMessageRequest) (*NotificationMessage, error)
	GetNotificationTemplate(context.Context, *GetNotificationTemplateRequest) (*NotificationTemplate, error)
	ListMyNotifications(context.Context, *ListNotificationMessagesRequest) (*ListNotificationMessagesResponse, error)
	ListNotificationMessages(context.Context, *ListNotificationMessagesRequest) (*ListNotificationMessagesResponse, error)
	ListNotificationTemplates(context.Context, *ListNotificationTemplatesRequest) (*ListNotificationTemplatesResponse, error)
	MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*emptypb.Empty, error)
	MarkNotificationsRead(context.Context, *MarkNotificationsReadRequest) (*emptypb.Empty, error)
	SendInAppNotification(context.Context, *SendInAppNotificationRequest) (*SendInAppNotificationResponse, error)
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	UpdateNotificationTemplate(context.Context, *UpdateNotificationTemplateRequest) (*NotificationTemplate, error)
}

func RegisterNotificationServiceHTTPServer(s *http.Server, srv NotificationServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/platform/v1/notification-templates", _NotificationService_ListNotificationTemplates0_HTTP_Handler(srv))
	r.GET("/platform/v1/notification-templates/{id}", _NotificationService_GetNotificationTemplate0_HTTP_Handler(srv))
	r.POST("/platform/v1/notification-templates", _NotificationService_CreateNotificationTemplate0_HTTP_Handler(srv))
	r.PUT("/platform/v1/notification-templates/{id}", _NotificationService_UpdateNotificationTemplate0_HTTP_Handler(srv))
	r.DELETE("/platform/v1/notification-templates/{id}", _NotificationService_DeleteNotificationTemplate0_HTTP_Handler(srv))
	r.POST("/platform/v1/notifications:send-in-app", _NotificationService_SendInAppNotification0_HTTP_Handler(srv))
	r.POST("/platform/v1/notifications:send", _NotificationService_SendNotification0_HTTP_Handler(srv))
	r.GET("/platform/v1/notification-messages", _NotificationService_ListNotificationMessages0_HTTP_Handler(srv))
	r.GET("/platform/v1/notification-messages/{id}", _NotificationService_GetNotificationMessage0_HTTP_Handler(srv))
	r.GET("/platform/v1/my/notifications", _NotificationService_ListMyNotifications0_HTTP_Handler(srv))
	r.GET("/platform/v1/my/notifications:unread-count", _NotificationService_CountMyUnreadNotifications0_HTTP_Handler(srv))
	r.POST("/platform/v1/my/notifications/{id}:read", _NotificationService_MarkNotificationRead0_HTTP_Handler(srv))
	r.POST("/platform/v1/my/notifications:read", _NotificationService_MarkNotificationsRead0_HTTP_Handler(srv))
}

func _NotificationService_ListNotificationTemplates0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceListNotificationTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotificationTemplates(ctx, req.(*ListNotificationTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationTemplatesResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_GetNotificationTemplate0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNotificationTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceGetNotificationTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNotificationTemplate(ctx, req.(*GetNotificationTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationTemplate)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_CreateNotificationTemplate0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNotificationTemplateRequest
		if err := ctx.Bind(&in.Template); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceCreateNotificationTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNotificationTemplate(ctx, req.(*CreateNotificationTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationTemplate)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_UpdateNotificationTemplate0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateNotificationTemplateRequest
		if err := ctx.Bind(&in.Template); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceUpdateNotificationTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNotificationTemplate(ctx, req.(*UpdateNotificationTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationTemplate)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_DeleteNotificationTemplate0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteNotificationTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceDeleteNotificationTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteNotificationTemplate(ctx, req.(*DeleteNotificationTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_SendInAppNotification0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendInAppNotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceSendInAppNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendInAppNotification(ctx, req.(*SendInAppNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendInAppNotificationResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_SendNotification0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendNotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceSendNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendNotification(ctx, req.(*SendNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendNotificationResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_ListNotificationMessages0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceListNotificationMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotificationMessages(ctx, req.(*ListNotificationMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_GetNotificationMessage0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNotificationMessageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceGetNotificationMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNotificationMessage(ctx, req.(*GetNotificationMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationMessage)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_ListMyNotifications0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceListMyNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyNotifications(ctx, req.(*ListNotificationMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_CountMyUnreadNotifications0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CountMyUnreadNotificationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceCountMyUnreadNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CountMyUnreadNotifications(ctx, req.(*CountMyUnreadNotificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CountMyUnreadNotificationsResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_MarkNotificationRead0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkNotificationReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceMarkNotificationRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkNotificationRead(ctx, req.(*MarkNotificationReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_MarkNotificationsRead0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkNotificationsReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceMarkNotificationsRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkNotificationsRead(ctx, req.(*MarkNotificationsReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type NotificationServiceHTTPClient interface {
	CountMyUnreadNotifications(ctx context.Context, req *CountMyUnreadNotificationsRequest, opts ...http.CallOption) (rsp *CountMyUnreadNotificationsResponse, err error)
	CreateNotificationTemplate(ctx context.Context, req *CreateNotificationTemplateRequest, opts ...http.CallOption) (rsp *NotificationTemplate, err error)
	DeleteNotificationTemplate(ctx context.Context, req *DeleteNotificationTemplateRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetNotificationMessage(ctx context.Context, req *GetNotificationMessageRequest, opts ...http.CallOption) (rsp *NotificationMessage, err error)
	GetNotificationTemplate(ctx context.Context, req *GetNotificationTemplateRequest, opts ...http.CallOption) (rsp *NotificationTemplate, err error)
	ListMyNotifications(ctx context.Context, req *ListNotificationMessagesRequest, opts ...http.CallOption) (rsp *ListNotificationMessagesResponse, err error)
	ListNotificationMessages(ctx context.Context, req *ListNotificationMessagesRequest, opts ...http.CallOption) (rsp *ListNotificationMessagesResponse, err error)
	ListNotificationTemplates(ctx context.Context, req *ListNotificationTemplatesRequest, opts ...http.CallOption) (rsp *ListNotificationTemplatesResponse, err error)
	MarkNotificationRead(ctx context.Context, req *MarkNotificationReadRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	MarkNotificationsRead(ctx context.Context, req *MarkNotificationsReadRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	SendInAppNotification(ctx context.Context, req *SendInAppNotificationRequest, opts ...http.CallOption) (rsp *SendInAppNotificationResponse, err error)
	SendNotification(ctx context.Context, req *SendNotificationRequest, opts ...http.CallOption) (rsp *SendNotificationResponse, err error)
	UpdateNotificationTemplate(ctx context.Context, req *UpdateNotificationTemplateRequest, opts ...http.CallOption) (rsp *NotificationTemplate, err error)
}

type NotificationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationServiceHTTPClient(client *http.Client) NotificationServiceHTTPClient {
	return &NotificationServiceHTTPClientImpl{client}
}

func (c *NotificationServiceHTTPClientImpl) CountMyUnreadNotifications(ctx context.Context, in *CountMyUnreadNotificationsRequest, opts ...http.CallOption) (*CountMyUnreadNotificationsResponse, error) {
	var out CountMyUnreadNotificationsResponse
	pattern := "/platform/v1/my/notifications:unread-count"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceCountMyUnreadNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) CreateNotificationTemplate(ctx context.Context, in *CreateNotificationTemplateRequest, opts ...http.CallOption) (*NotificationTemplate, error) {
	var out NotificationTemplate
	pattern := "/platform/v1/notification-templates"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceCreateNotificationTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Template, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) DeleteNotificationTemplate(ctx context.Context, in *DeleteNotificationTemplateRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/notification-templates/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceDeleteNotificationTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) GetNotificationMessage(ctx context.Context, in *GetNotificationMessageRequest, opts ...http.CallOption) (*NotificationMessage, error) {
	var out NotificationMessage
	pattern := "/platform/v1/notification-messages/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceGetNotificationMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) GetNotificationTemplate(ctx context.Context, in *GetNotificationTemplateRequest, opts ...http.CallOption) (*NotificationTemplate, error) {
	var out NotificationTemplate
	pattern := "/platform/v1/notification-templates/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceGetNotificationTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) ListMyNotifications(ctx context.Context, in *ListNotificationMessagesRequest, opts ...http.CallOption) (*ListNotificationMessagesResponse, error) {
	var out ListNotificationMessagesResponse
	pattern := "/platform/v1/my/notifications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceListMyNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) ListNotificationMessages(ctx context.Context, in *ListNotificationMessagesRequest, opts ...http.CallOption) (*ListNotificationMessagesResponse, error) {
	var out ListNotificationMessagesResponse
	pattern := "/platform/v1/notification-messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceListNotificationMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) ListNotificationTemplates(ctx context.Context, in *ListNotificationTemplatesRequest, opts ...http.CallOption) (*ListNotificationTemplatesResponse, error) {
	var out ListNotificationTemplatesResponse
	pattern := "/platform/v1/notification-templates"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotificationServiceListNotificationTemplates))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/my/notifications/{id}:read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceMarkNotificationRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) MarkNotificationsRead(ctx context.Context, in *MarkNotificationsReadRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/platform/v1/my/notifications:read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceMarkNotificationsRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) SendInAppNotification(ctx context.Context, in *SendInAppNotificationRequest, opts ...http.CallOption) (*SendInAppNotificationResponse, error) {
	var out SendInAppNotificationResponse
	pattern := "/platform/v1/notifications:send-in-app"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceSendInAppNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...http.CallOption) (*SendNotificationResponse, error) {
	var out SendNotificationResponse
	pattern := "/platform/v1/notifications:send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceSendNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) UpdateNotificationTemplate(ctx context.Context, in *UpdateNotificationTemplateRequest, opts ...http.CallOption) (*NotificationTemplate, error) {
	var out NotificationTemplate
	pattern := "/platform/v1/notification-templates/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceUpdateNotificationTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Template, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
