// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/service/v1/session.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Ip            *string                `protobuf:"bytes,5,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	UserAgent     *string                `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	Current       bool                   `protobuf:"varint,7,opt,name=current,proto3" json:"current,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	LastActiveAt  *string                `protobuf:"bytes,9,opt,name=last_active_at,json=lastActiveAt,proto3,oneof" json:"last_active_at,omitempty"`
	ExpiresAt     *string                `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_platform_service_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Session) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *Session) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *Session) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *Session) GetLastActiveAt() string {
	if x != nil && x.LastActiveAt != nil {
		return *x.LastActiveAt
	}
	return ""
}

func (x *Session) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        *uint32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Ip            *string                `protobuf:"bytes,5,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_platform_service_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListSessionsRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ListSessionsRequest) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_platform_service_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsResponse) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListMySessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySessionsRequest) Reset() {
	*x = ListMySessionsRequest{}
	mi := &file_platform_service_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySessionsRequest) ProtoMessage() {}

func (x *ListMySessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySessionsRequest.ProtoReflect.Descriptor instead.
func (*ListMySessionsRequest) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{3}
}

type ListMySessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySessionsResponse) Reset() {
	*x = ListMySessionsResponse{}
	mi := &file_platform_service_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySessionsResponse) ProtoMessage() {}

func (x *ListMySessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySessionsResponse.ProtoReflect.Descriptor instead.
func (*ListMySessionsResponse) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ListMySessionsResponse) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_platform_service_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_platform_service_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_service_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_platform_service_v1_session_proto_rawDescGZIP(), []int{6}
}

var File_platform_service_v1_session_proto protoreflect.FileDescriptor

const file_platform_service_v1_session_proto_rawDesc = "" +
	"\n" +
	"!platform/service/v1/session.proto\x12\x13platform.service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xf8\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x13\n" +
	"\x02ip\x18\x05 \x01(\tH\x00R\x02ip\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tH\x01R\tuserAgent\x88\x01\x01\x12\x18\n" +
	"\acurrent\x18\a \x01(\bR\acurrent\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\tH\x02R\tcreatedAt\x88\x01\x01\x12)\n" +
	"\x0elast_active_at\x18\t \x01(\tH\x03R\flastActiveAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tH\x04R\texpiresAt\x88\x01\x01B\x05\n" +
	"\x03_ipB\r\n" +
	"\v_user_agentB\r\n" +
	"\v_created_atB\x11\n" +
	"\x0f_last_active_atB\r\n" +
	"\v_expires_at\"\xd7\x01\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\rH\x00R\x06userId\x88\x01\x01\x12(\n" +
	"\busername\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18dH\x01R\busername\x88\x01\x01\x12\x1c\n" +
	"\x02ip\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18@H\x02R\x02ip\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\v\n" +
	"\t_usernameB\x05\n" +
	"\x03_ip\"\x88\x01\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.platform.service.v1.SessionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\x17\n" +
	"\x15ListMySessionsRequest\"L\n" +
	"\x16ListMySessionsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.platform.service.v1.SessionR\x05items\"1\n" +
	"\x14RevokeSessionRequest\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x10\x18@R\x02id\"\x17\n" +
	"\x15RevokeSessionResponse2\xb2\x03\n" +
	"\x0eSessionService\x12\x82\x01\n" +
	"\fListSessions\x12(.platform.service.v1.ListSessionsRequest\x1a).platform.service.v1.ListSessionsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/platform/v1/sessions\x12\x8d\x01\n" +
	"\x0eListMySessions\x12*.platform.service.v1.ListMySessionsRequest\x1a+.platform.service.v1.ListMySessionsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/platform/v1/sessions/mine\x12\x8a\x01\n" +
	"\rRevokeSession\x12).platform.service.v1.RevokeSessionRequest\x1a*.platform.service.v1.RevokeSessionResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/platform/v1/sessions/{id}B\xc1\x01\n" +
	"\x17com.platform.service.v1B\fSessionProtoP\x01Z*backend-service/api/platform/service/v1;v1\xa2\x02\x03PSX\xaa\x02\x13Platform.Service.V1\xca\x02\x13Platform\\Service\\V1\xe2\x02\x1fPlatform\\Service\\V1\\GPBMetadata\xea\x02\x15Platform::Service::V1b\x06proto3"

var (
	file_platform_service_v1_session_proto_rawDescOnce sync.Once
	file_platform_service_v1_session_proto_rawDescData []byte
)

func file_platform_service_v1_session_proto_rawDescGZIP() []byte {
	file_platform_service_v1_session_proto_rawDescOnce.Do(func() {
		file_platform_service_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_service_v1_session_proto_rawDesc), len(file_platform_service_v1_session_proto_rawDesc)))
	})
	return file_platform_service_v1_session_proto_rawDescData
}

var file_platform_service_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_platform_service_v1_session_proto_goTypes = []any{
	(*Session)(nil),                // 0: platform.service.v1.Session
	(*ListSessionsRequest)(nil),    // 1: platform.service.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 2: platform.service.v1.ListSessionsResponse
	(*ListMySessionsRequest)(nil),  // 3: platform.service.v1.ListMySessionsRequest
	(*ListMySessionsResponse)(nil), // 4: platform.service.v1.ListMySessionsResponse
	(*RevokeSessionRequest)(nil),   // 5: platform.service.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),  // 6: platform.service.v1.RevokeSessionResponse
}
var file_platform_service_v1_session_proto_depIdxs = []int32{
	0, // 0: platform.service.v1.ListSessionsResponse.items:type_name -> platform.service.v1.Session
	0, // 1: platform.service.v1.ListMySessionsResponse.items:type_name -> platform.service.v1.Session
	1, // 2: platform.service.v1.SessionService.ListSessions:input_type -> platform.service.v1.ListSessionsRequest
	3, // 3: platform.service.v1.SessionService.ListMySessions:input_type -> platform.service.v1.ListMySessionsRequest
	5, // 4: platform.service.v1.SessionService.RevokeSession:input_type -> platform.service.v1.RevokeSessionRequest
	2, // 5: platform.service.v1.SessionService.ListSessions:output_type -> platform.service.v1.ListSessionsResponse
	4, // 6: platform.service.v1.SessionService.ListMySessions:output_type -> platform.service.v1.ListMySessionsResponse
	6, // 7: platform.service.v1.SessionService.RevokeSession:output_type -> platform.service.v1.RevokeSessionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_platform_service_v1_session_proto_init() }
func file_platform_service_v1_session_proto_init() {
	if File_platform_service_v1_session_proto != nil {
		return
	}
	file_platform_service_v1_session_proto_msgTypes[0].OneofWrappers = []any{}
	file_platform_service_v1_session_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_service_v1_session_proto_rawDesc), len(file_platform_service_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_service_v1_session_proto_goTypes,
		DependencyIndexes: file_platform_service_v1_session_proto_depIdxs,
		MessageInfos:      file_platform_service_v1_session_proto_msgTypes,
	}.Build()
	File_platform_service_v1_session_proto = out.File
	file_platform_service_v1_session_proto_goTypes = nil
	file_platform_service_v1_session_proto_depIdxs = nil
}
