// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: platform/service/v1/storage_provider.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StorageProvider with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StorageProvider) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StorageProvider with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StorageProviderMultiError, or nil if none found.
func (m *StorageProvider) ValidateAll() error {
	return m.validate(true)
}

func (m *StorageProvider) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Code

	// no validation rules for Name

	// no validation rules for Type

	if m.Endpoint != nil {
		// no validation rules for Endpoint
	}

	if m.Region != nil {
		// no validation rules for Region
	}

	if m.AccessKey != nil {
		// no validation rules for AccessKey
	}

	if m.SecretKey != nil {
		// no validation rules for SecretKey
	}

	if m.SessionToken != nil {
		// no validation rules for SessionToken
	}

	if m.UseSsl != nil {
		// no validation rules for UseSsl
	}

	if m.ForcePathStyle != nil {
		// no validation rules for ForcePathStyle
	}

	if m.PublicBaseUrl != nil {
		// no validation rules for PublicBaseUrl
	}

	if m.DefaultBucket != nil {
		// no validation rules for DefaultBucket
	}

	if m.LocalBasePath != nil {
		// no validation rules for LocalBasePath
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.IsDefault != nil {
		// no validation rules for IsDefault
	}

	if m.HealthStatus != nil {
		// no validation rules for HealthStatus
	}

	if m.LastCheckedAt != nil {
		// no validation rules for LastCheckedAt
	}

	if m.CreatedAt != nil {
		// no validation rules for CreatedAt
	}

	if m.UpdatedAt != nil {
		// no validation rules for UpdatedAt
	}

	if m.DeletedAt != nil {
		// no validation rules for DeletedAt
	}

	if m.Remark != nil {
		// no validation rules for Remark
	}

	if m.SecretConfigured != nil {
		// no validation rules for SecretConfigured
	}

	if len(errors) > 0 {
		return StorageProviderMultiError(errors)
	}

	return nil
}

// StorageProviderMultiError is an error wrapping multiple validation errors
// returned by StorageProvider.ValidateAll() if the designated constraints
// aren't met.
type StorageProviderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StorageProviderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StorageProviderMultiError) AllErrors() []error { return m }

// StorageProviderValidationError is the validation error returned by
// StorageProvider.Validate if the designated constraints aren't met.
type StorageProviderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StorageProviderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StorageProviderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StorageProviderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StorageProviderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StorageProviderValidationError) ErrorName() string { return "StorageProviderValidationError" }

// Error satisfies the builtin error interface
func (e StorageProviderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStorageProvider.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StorageProviderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StorageProviderValidationError{}

// Validate checks the field values on CreateStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateStorageProviderRequestMultiError, or nil if none found.
func (m *CreateStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateStorageProviderRequestValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateStorageProviderRequestMultiError(errors)
	}

	return nil
}

// CreateStorageProviderRequestMultiError is an error wrapping multiple
// validation errors returned by CreateStorageProviderRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateStorageProviderRequestMultiError) AllErrors() []error { return m }

// CreateStorageProviderRequestValidationError is the validation error returned
// by CreateStorageProviderRequest.Validate if the designated constraints
// aren't met.
type CreateStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateStorageProviderRequestValidationError) ErrorName() string {
	return "CreateStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateStorageProviderRequestValidationError{}

// Validate checks the field values on CreateStorageProviderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateStorageProviderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateStorageProviderResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateStorageProviderResponseMultiError, or nil if none found.
func (m *CreateStorageProviderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateStorageProviderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateStorageProviderResponseValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateStorageProviderResponseMultiError(errors)
	}

	return nil
}

// CreateStorageProviderResponseMultiError is an error wrapping multiple
// validation errors returned by CreateStorageProviderResponse.ValidateAll()
// if the designated constraints aren't met.
type CreateStorageProviderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateStorageProviderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateStorageProviderResponseMultiError) AllErrors() []error { return m }

// CreateStorageProviderResponseValidationError is the validation error
// returned by CreateStorageProviderResponse.Validate if the designated
// constraints aren't met.
type CreateStorageProviderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateStorageProviderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateStorageProviderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateStorageProviderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateStorageProviderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateStorageProviderResponseValidationError) ErrorName() string {
	return "CreateStorageProviderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateStorageProviderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateStorageProviderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateStorageProviderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateStorageProviderResponseValidationError{}

// Validate checks the field values on UpdateStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateStorageProviderRequestMultiError, or nil if none found.
func (m *UpdateStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateStorageProviderRequestValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateStorageProviderRequestMultiError(errors)
	}

	return nil
}

// UpdateStorageProviderRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateStorageProviderRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateStorageProviderRequestMultiError) AllErrors() []error { return m }

// UpdateStorageProviderRequestValidationError is the validation error returned
// by UpdateStorageProviderRequest.Validate if the designated constraints
// aren't met.
type UpdateStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateStorageProviderRequestValidationError) ErrorName() string {
	return "UpdateStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateStorageProviderRequestValidationError{}

// Validate checks the field values on UpdateStorageProviderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateStorageProviderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateStorageProviderResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateStorageProviderResponseMultiError, or nil if none found.
func (m *UpdateStorageProviderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateStorageProviderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateStorageProviderResponseValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateStorageProviderResponseMultiError(errors)
	}

	return nil
}

// UpdateStorageProviderResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateStorageProviderResponse.ValidateAll()
// if the designated constraints aren't met.
type UpdateStorageProviderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateStorageProviderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateStorageProviderResponseMultiError) AllErrors() []error { return m }

// UpdateStorageProviderResponseValidationError is the validation error
// returned by UpdateStorageProviderResponse.Validate if the designated
// constraints aren't met.
type UpdateStorageProviderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateStorageProviderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateStorageProviderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateStorageProviderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateStorageProviderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateStorageProviderResponseValidationError) ErrorName() string {
	return "UpdateStorageProviderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateStorageProviderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateStorageProviderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateStorageProviderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateStorageProviderResponseValidationError{}

// Validate checks the field values on DeleteStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteStorageProviderRequestMultiError, or nil if none found.
func (m *DeleteStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteStorageProviderRequestMultiError(errors)
	}

	return nil
}

// DeleteStorageProviderRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteStorageProviderRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteStorageProviderRequestMultiError) AllErrors() []error { return m }

// DeleteStorageProviderRequestValidationError is the validation error returned
// by DeleteStorageProviderRequest.Validate if the designated constraints
// aren't met.
type DeleteStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteStorageProviderRequestValidationError) ErrorName() string {
	return "DeleteStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteStorageProviderRequestValidationError{}

// Validate checks the field values on DeleteStorageProviderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteStorageProviderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteStorageProviderResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteStorageProviderResponseMultiError, or nil if none found.
func (m *DeleteStorageProviderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteStorageProviderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteStorageProviderResponseMultiError(errors)
	}

	return nil
}

// DeleteStorageProviderResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteStorageProviderResponse.ValidateAll()
// if the designated constraints aren't met.
type DeleteStorageProviderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteStorageProviderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteStorageProviderResponseMultiError) AllErrors() []error { return m }

// DeleteStorageProviderResponseValidationError is the validation error
// returned by DeleteStorageProviderResponse.Validate if the designated
// constraints aren't met.
type DeleteStorageProviderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteStorageProviderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteStorageProviderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteStorageProviderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteStorageProviderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteStorageProviderResponseValidationError) ErrorName() string {
	return "DeleteStorageProviderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteStorageProviderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteStorageProviderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteStorageProviderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteStorageProviderResponseValidationError{}

// Validate checks the field values on GetStorageProviderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetStorageProviderRequestMultiError, or nil if none found.
func (m *GetStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetStorageProviderRequestMultiError(errors)
	}

	return nil
}

// GetStorageProviderRequestMultiError is an error wrapping multiple validation
// errors returned by GetStorageProviderRequest.ValidateAll() if the
// designated constraints aren't met.
type GetStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetStorageProviderRequestMultiError) AllErrors() []error { return m }

// GetStorageProviderRequestValidationError is the validation error returned by
// GetStorageProviderRequest.Validate if the designated constraints aren't met.
type GetStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetStorageProviderRequestValidationError) ErrorName() string {
	return "GetStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetStorageProviderRequestValidationError{}

// Validate checks the field values on ListStorageProvidersRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListStorageProvidersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListStorageProvidersRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListStorageProvidersRequestMultiError, or nil if none found.
func (m *ListStorageProvidersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListStorageProvidersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageToken

	// no validation rules for PageSize

	if m.NoPaging != nil {
		// no validation rules for NoPaging
	}

	if m.Code != nil {
		// no validation rules for Code
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Type != nil {
		// no validation rules for Type
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.IsDefault != nil {
		// no validation rules for IsDefault
	}

	if len(errors) > 0 {
		return ListStorageProvidersRequestMultiError(errors)
	}

	return nil
}

// ListStorageProvidersRequestMultiError is an error wrapping multiple
// validation errors returned by ListStorageProvidersRequest.ValidateAll() if
// the designated constraints aren't met.
type ListStorageProvidersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListStorageProvidersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListStorageProvidersRequestMultiError) AllErrors() []error { return m }

// ListStorageProvidersRequestValidationError is the validation error returned
// by ListStorageProvidersRequest.Validate if the designated constraints
// aren't met.
type ListStorageProvidersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListStorageProvidersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListStorageProvidersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListStorageProvidersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListStorageProvidersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListStorageProvidersRequestValidationError) ErrorName() string {
	return "ListStorageProvidersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListStorageProvidersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListStorageProvidersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListStorageProvidersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListStorageProvidersRequestValidationError{}

// Validate checks the field values on ListStorageProvidersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListStorageProvidersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListStorageProvidersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListStorageProvidersResponseMultiError, or nil if none found.
func (m *ListStorageProvidersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListStorageProvidersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListStorageProvidersResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListStorageProvidersResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListStorageProvidersResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListStorageProvidersResponseMultiError(errors)
	}

	return nil
}

// ListStorageProvidersResponseMultiError is an error wrapping multiple
// validation errors returned by ListStorageProvidersResponse.ValidateAll() if
// the designated constraints aren't met.
type ListStorageProvidersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListStorageProvidersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListStorageProvidersResponseMultiError) AllErrors() []error { return m }

// ListStorageProvidersResponseValidationError is the validation error returned
// by ListStorageProvidersResponse.Validate if the designated constraints
// aren't met.
type ListStorageProvidersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListStorageProvidersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListStorageProvidersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListStorageProvidersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListStorageProvidersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListStorageProvidersResponseValidationError) ErrorName() string {
	return "ListStorageProvidersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListStorageProvidersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListStorageProvidersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListStorageProvidersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListStorageProvidersResponseValidationError{}

// Validate checks the field values on SetDefaultStorageProviderRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *SetDefaultStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetDefaultStorageProviderRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SetDefaultStorageProviderRequestMultiError, or nil if none found.
func (m *SetDefaultStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetDefaultStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SetDefaultStorageProviderRequestMultiError(errors)
	}

	return nil
}

// SetDefaultStorageProviderRequestMultiError is an error wrapping multiple
// validation errors returned by
// SetDefaultStorageProviderRequest.ValidateAll() if the designated
// constraints aren't met.
type SetDefaultStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetDefaultStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetDefaultStorageProviderRequestMultiError) AllErrors() []error { return m }

// SetDefaultStorageProviderRequestValidationError is the validation error
// returned by SetDefaultStorageProviderRequest.Validate if the designated
// constraints aren't met.
type SetDefaultStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetDefaultStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetDefaultStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetDefaultStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetDefaultStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetDefaultStorageProviderRequestValidationError) ErrorName() string {
	return "SetDefaultStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetDefaultStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetDefaultStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetDefaultStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetDefaultStorageProviderRequestValidationError{}

// Validate checks the field values on SetDefaultStorageProviderResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *SetDefaultStorageProviderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetDefaultStorageProviderResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// SetDefaultStorageProviderResponseMultiError, or nil if none found.
func (m *SetDefaultStorageProviderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetDefaultStorageProviderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetDefaultStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetDefaultStorageProviderResponseValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetDefaultStorageProviderResponseValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetDefaultStorageProviderResponseMultiError(errors)
	}

	return nil
}

// SetDefaultStorageProviderResponseMultiError is an error wrapping multiple
// validation errors returned by
// SetDefaultStorageProviderResponse.ValidateAll() if the designated
// constraints aren't met.
type SetDefaultStorageProviderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetDefaultStorageProviderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetDefaultStorageProviderResponseMultiError) AllErrors() []error { return m }

// SetDefaultStorageProviderResponseValidationError is the validation error
// returned by SetDefaultStorageProviderResponse.Validate if the designated
// constraints aren't met.
type SetDefaultStorageProviderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetDefaultStorageProviderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetDefaultStorageProviderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetDefaultStorageProviderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetDefaultStorageProviderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetDefaultStorageProviderResponseValidationError) ErrorName() string {
	return "SetDefaultStorageProviderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetDefaultStorageProviderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetDefaultStorageProviderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetDefaultStorageProviderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetDefaultStorageProviderResponseValidationError{}

// Validate checks the field values on TestStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TestStorageProviderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestStorageProviderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestStorageProviderRequestMultiError, or nil if none found.
func (m *TestStorageProviderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TestStorageProviderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetProvider()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestStorageProviderRequestValidationError{
					field:  "Provider",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProvider()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestStorageProviderRequestValidationError{
				field:  "Provider",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TestStorageProviderRequestMultiError(errors)
	}

	return nil
}

// TestStorageProviderRequestMultiError is an error wrapping multiple
// validation errors returned by TestStorageProviderRequest.ValidateAll() if
// the designated constraints aren't met.
type TestStorageProviderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestStorageProviderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestStorageProviderRequestMultiError) AllErrors() []error { return m }

// TestStorageProviderRequestValidationError is the validation error returned
// by TestStorageProviderRequest.Validate if the designated constraints aren't met.
type TestStorageProviderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestStorageProviderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestStorageProviderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestStorageProviderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestStorageProviderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestStorageProviderRequestValidationError) ErrorName() string {
	return "TestStorageProviderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TestStorageProviderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestStorageProviderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestStorageProviderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestStorageProviderRequestValidationError{}

// Validate checks the field values on TestStorageProviderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TestStorageProviderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestStorageProviderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestStorageProviderResponseMultiError, or nil if none found.
func (m *TestStorageProviderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TestStorageProviderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Healthy

	// no validation rules for Message

	if len(errors) > 0 {
		return TestStorageProviderResponseMultiError(errors)
	}

	return nil
}

// TestStorageProviderResponseMultiError is an error wrapping multiple
// validation errors returned by TestStorageProviderResponse.ValidateAll() if
// the designated constraints aren't met.
type TestStorageProviderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestStorageProviderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestStorageProviderResponseMultiError) AllErrors() []error { return m }

// TestStorageProviderResponseValidationError is the validation error returned
// by TestStorageProviderResponse.Validate if the designated constraints
// aren't met.
type TestStorageProviderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestStorageProviderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestStorageProviderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestStorageProviderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestStorageProviderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestStorageProviderResponseValidationError) ErrorName() string {
	return "TestStorageProviderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TestStorageProviderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestStorageProviderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestStorageProviderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestStorageProviderResponseValidationError{}
