// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: platform/service/v1/tenant_menu_permission_group.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups_FullMethodName           = "/platform.service.v1.TenantMenuPermissionGroupService/ListTenantMenuPermissionGroups"
	TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup_FullMethodName             = "/platform.service.v1.TenantMenuPermissionGroupService/GetTenantMenuPermissionGroup"
	TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup_FullMethodName          = "/platform.service.v1.TenantMenuPermissionGroupService/CreateTenantMenuPermissionGroup"
	TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup_FullMethodName          = "/platform.service.v1.TenantMenuPermissionGroupService/UpdateTenantMenuPermissionGroup"
	TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup_FullMethodName          = "/platform.service.v1.TenantMenuPermissionGroupService/DeleteTenantMenuPermissionGroup"
	TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus_FullMethodName    = "/platform.service.v1.TenantMenuPermissionGroupService/UpdateTenantMenuPermissionGroupStatus"
	TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions_FullMethodName    = "/platform.service.v1.TenantMenuPermissionGroupService/ListTenantMenuPermissionGroupVersions"
	TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion_FullMethodName  = "/platform.service.v1.TenantMenuPermissionGroupService/PublishTenantMenuPermissionGroupVersion"
	TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion_FullMethodName = "/platform.service.v1.TenantMenuPermissionGroupService/RollbackTenantMenuPermissionGroupVersion"
)

// TenantMenuPermissionGroupServiceClient is the client API for TenantMenuPermissionGroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 菜单权限组服务
type TenantMenuPermissionGroupServiceClient interface {
	// 获取菜单权限组列表
	ListTenantMenuPermissionGroups(ctx context.Context, in *ListTenantMenuPermissionGroupsRequest, opts ...grpc.CallOption) (*ListTenantMenuPermissionGroupsResponse, error)
	// 获取菜单权限组
	GetTenantMenuPermissionGroup(ctx context.Context, in *GetTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*TenantMenuPermissionGroup, error)
	// 创建菜单权限组
	CreateTenantMenuPermissionGroup(ctx context.Context, in *CreateTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*CreateTenantMenuPermissionGroupResponse, error)
	// 更新菜单权限组
	UpdateTenantMenuPermissionGroup(ctx context.Context, in *UpdateTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*UpdateTenantMenuPermissionGroupResponse, error)
	// 删除菜单权限组
	DeleteTenantMenuPermissionGroup(ctx context.Context, in *DeleteTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*DeleteTenantMenuPermissionGroupResponse, error)
	// 更新菜单权限组状态
	UpdateTenantMenuPermissionGroupStatus(ctx context.Context, in *UpdateTenantMenuPermissionGroupStatusRequest, opts ...grpc.CallOption) (*UpdateTenantMenuPermissionGroupStatusResponse, error)
	ListTenantMenuPermissionGroupVersions(ctx context.Context, in *ListTenantMenuPermissionGroupVersionsRequest, opts ...grpc.CallOption) (*ListTenantMenuPermissionGroupVersionsResponse, error)
	PublishTenantMenuPermissionGroupVersion(ctx context.Context, in *PublishTenantMenuPermissionGroupVersionRequest, opts ...grpc.CallOption) (*PublishTenantMenuPermissionGroupVersionResponse, error)
	RollbackTenantMenuPermissionGroupVersion(ctx context.Context, in *RollbackTenantMenuPermissionGroupVersionRequest, opts ...grpc.CallOption) (*RollbackTenantMenuPermissionGroupVersionResponse, error)
}

type tenantMenuPermissionGroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantMenuPermissionGroupServiceClient(cc grpc.ClientConnInterface) TenantMenuPermissionGroupServiceClient {
	return &tenantMenuPermissionGroupServiceClient{cc}
}

func (c *tenantMenuPermissionGroupServiceClient) ListTenantMenuPermissionGroups(ctx context.Context, in *ListTenantMenuPermissionGroupsRequest, opts ...grpc.CallOption) (*ListTenantMenuPermissionGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantMenuPermissionGroupsResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) GetTenantMenuPermissionGroup(ctx context.Context, in *GetTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*TenantMenuPermissionGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantMenuPermissionGroup)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) CreateTenantMenuPermissionGroup(ctx context.Context, in *CreateTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*CreateTenantMenuPermissionGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantMenuPermissionGroupResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) UpdateTenantMenuPermissionGroup(ctx context.Context, in *UpdateTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*UpdateTenantMenuPermissionGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantMenuPermissionGroupResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) DeleteTenantMenuPermissionGroup(ctx context.Context, in *DeleteTenantMenuPermissionGroupRequest, opts ...grpc.CallOption) (*DeleteTenantMenuPermissionGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantMenuPermissionGroupResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) UpdateTenantMenuPermissionGroupStatus(ctx context.Context, in *UpdateTenantMenuPermissionGroupStatusRequest, opts ...grpc.CallOption) (*UpdateTenantMenuPermissionGroupStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantMenuPermissionGroupStatusResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) ListTenantMenuPermissionGroupVersions(ctx context.Context, in *ListTenantMenuPermissionGroupVersionsRequest, opts ...grpc.CallOption) (*ListTenantMenuPermissionGroupVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantMenuPermissionGroupVersionsResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) PublishTenantMenuPermissionGroupVersion(ctx context.Context, in *PublishTenantMenuPermissionGroupVersionRequest, opts ...grpc.CallOption) (*PublishTenantMenuPermissionGroupVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishTenantMenuPermissionGroupVersionResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMenuPermissionGroupServiceClient) RollbackTenantMenuPermissionGroupVersion(ctx context.Context, in *RollbackTenantMenuPermissionGroupVersionRequest, opts ...grpc.CallOption) (*RollbackTenantMenuPermissionGroupVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackTenantMenuPermissionGroupVersionResponse)
	err := c.cc.Invoke(ctx, TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantMenuPermissionGroupServiceServer is the server API for TenantMenuPermissionGroupService service.
// All implementations must embed UnimplementedTenantMenuPermissionGroupServiceServer
// for forward compatibility.
//
// 菜单权限组服务
type TenantMenuPermissionGroupServiceServer interface {
	// 获取菜单权限组列表
	ListTenantMenuPermissionGroups(context.Context, *ListTenantMenuPermissionGroupsRequest) (*ListTenantMenuPermissionGroupsResponse, error)
	// 获取菜单权限组
	GetTenantMenuPermissionGroup(context.Context, *GetTenantMenuPermissionGroupRequest) (*TenantMenuPermissionGroup, error)
	// 创建菜单权限组
	CreateTenantMenuPermissionGroup(context.Context, *CreateTenantMenuPermissionGroupRequest) (*CreateTenantMenuPermissionGroupResponse, error)
	// 更新菜单权限组
	UpdateTenantMenuPermissionGroup(context.Context, *UpdateTenantMenuPermissionGroupRequest) (*UpdateTenantMenuPermissionGroupResponse, error)
	// 删除菜单权限组
	DeleteTenantMenuPermissionGroup(context.Context, *DeleteTenantMenuPermissionGroupRequest) (*DeleteTenantMenuPermissionGroupResponse, error)
	// 更新菜单权限组状态
	UpdateTenantMenuPermissionGroupStatus(context.Context, *UpdateTenantMenuPermissionGroupStatusRequest) (*UpdateTenantMenuPermissionGroupStatusResponse, error)
	ListTenantMenuPermissionGroupVersions(context.Context, *ListTenantMenuPermissionGroupVersionsRequest) (*ListTenantMenuPermissionGroupVersionsResponse, error)
	PublishTenantMenuPermissionGroupVersion(context.Context, *PublishTenantMenuPermissionGroupVersionRequest) (*PublishTenantMenuPermissionGroupVersionResponse, error)
	RollbackTenantMenuPermissionGroupVersion(context.Context, *RollbackTenantMenuPermissionGroupVersionRequest) (*RollbackTenantMenuPermissionGroupVersionResponse, error)
	mustEmbedUnimplementedTenantMenuPermissionGroupServiceServer()
}

// UnimplementedTenantMenuPermissionGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantMenuPermissionGroupServiceServer struct{}

func (UnimplementedTenantMenuPermissionGroupServiceServer) ListTenantMenuPermissionGroups(context.Context, *ListTenantMenuPermissionGroupsRequest) (*ListTenantMenuPermissionGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantMenuPermissionGroups not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) GetTenantMenuPermissionGroup(context.Context, *GetTenantMenuPermissionGroupRequest) (*TenantMenuPermissionGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantMenuPermissionGroup not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) CreateTenantMenuPermissionGroup(context.Context, *CreateTenantMenuPermissionGroupRequest) (*CreateTenantMenuPermissionGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenantMenuPermissionGroup not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) UpdateTenantMenuPermissionGroup(context.Context, *UpdateTenantMenuPermissionGroupRequest) (*UpdateTenantMenuPermissionGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantMenuPermissionGroup not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) DeleteTenantMenuPermissionGroup(context.Context, *DeleteTenantMenuPermissionGroupRequest) (*DeleteTenantMenuPermissionGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenantMenuPermissionGroup not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) UpdateTenantMenuPermissionGroupStatus(context.Context, *UpdateTenantMenuPermissionGroupStatusRequest) (*UpdateTenantMenuPermissionGroupStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantMenuPermissionGroupStatus not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) ListTenantMenuPermissionGroupVersions(context.Context, *ListTenantMenuPermissionGroupVersionsRequest) (*ListTenantMenuPermissionGroupVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantMenuPermissionGroupVersions not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) PublishTenantMenuPermissionGroupVersion(context.Context, *PublishTenantMenuPermissionGroupVersionRequest) (*PublishTenantMenuPermissionGroupVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTenantMenuPermissionGroupVersion not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) RollbackTenantMenuPermissionGroupVersion(context.Context, *RollbackTenantMenuPermissionGroupVersionRequest) (*RollbackTenantMenuPermissionGroupVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTenantMenuPermissionGroupVersion not implemented")
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) mustEmbedUnimplementedTenantMenuPermissionGroupServiceServer() {
}
func (UnimplementedTenantMenuPermissionGroupServiceServer) testEmbeddedByValue() {}

// UnsafeTenantMenuPermissionGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantMenuPermissionGroupServiceServer will
// result in compilation errors.
type UnsafeTenantMenuPermissionGroupServiceServer interface {
	mustEmbedUnimplementedTenantMenuPermissionGroupServiceServer()
}

func RegisterTenantMenuPermissionGroupServiceServer(s grpc.ServiceRegistrar, srv TenantMenuPermissionGroupServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantMenuPermissionGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantMenuPermissionGroupService_ServiceDesc, srv)
}

func _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantMenuPermissionGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).ListTenantMenuPermissionGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).ListTenantMenuPermissionGroups(ctx, req.(*ListTenantMenuPermissionGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantMenuPermissionGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).GetTenantMenuPermissionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).GetTenantMenuPermissionGroup(ctx, req.(*GetTenantMenuPermissionGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantMenuPermissionGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).CreateTenantMenuPermissionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).CreateTenantMenuPermissionGroup(ctx, req.(*CreateTenantMenuPermissionGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantMenuPermissionGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).UpdateTenantMenuPermissionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).UpdateTenantMenuPermissionGroup(ctx, req.(*UpdateTenantMenuPermissionGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantMenuPermissionGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).DeleteTenantMenuPermissionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).DeleteTenantMenuPermissionGroup(ctx, req.(*DeleteTenantMenuPermissionGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantMenuPermissionGroupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).UpdateTenantMenuPermissionGroupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).UpdateTenantMenuPermissionGroupStatus(ctx, req.(*UpdateTenantMenuPermissionGroupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantMenuPermissionGroupVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).ListTenantMenuPermissionGroupVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).ListTenantMenuPermissionGroupVersions(ctx, req.(*ListTenantMenuPermissionGroupVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTenantMenuPermissionGroupVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).PublishTenantMenuPermissionGroupVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).PublishTenantMenuPermissionGroupVersion(ctx, req.(*PublishTenantMenuPermissionGroupVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTenantMenuPermissionGroupVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMenuPermissionGroupServiceServer).RollbackTenantMenuPermissionGroupVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMenuPermissionGroupServiceServer).RollbackTenantMenuPermissionGroupVersion(ctx, req.(*RollbackTenantMenuPermissionGroupVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantMenuPermissionGroupService_ServiceDesc is the grpc.ServiceDesc for TenantMenuPermissionGroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantMenuPermissionGroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.service.v1.TenantMenuPermissionGroupService",
	HandlerType: (*TenantMenuPermissionGroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTenantMenuPermissionGroups",
			Handler:    _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups_Handler,
		},
		{
			MethodName: "GetTenantMenuPermissionGroup",
			Handler:    _TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup_Handler,
		},
		{
			MethodName: "CreateTenantMenuPermissionGroup",
			Handler:    _TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup_Handler,
		},
		{
			MethodName: "UpdateTenantMenuPermissionGroup",
			Handler:    _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup_Handler,
		},
		{
			MethodName: "DeleteTenantMenuPermissionGroup",
			Handler:    _TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup_Handler,
		},
		{
			MethodName: "UpdateTenantMenuPermissionGroupStatus",
			Handler:    _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus_Handler,
		},
		{
			MethodName: "ListTenantMenuPermissionGroupVersions",
			Handler:    _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions_Handler,
		},
		{
			MethodName: "PublishTenantMenuPermissionGroupVersion",
			Handler:    _TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion_Handler,
		},
		{
			MethodName: "RollbackTenantMenuPermissionGroupVersion",
			Handler:    _TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/service/v1/tenant_menu_permission_group.proto",
}
