// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: platform/service/v1/tenant_menu_permission_group.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTenantMenuPermissionGroupServiceCreateTenantMenuPermissionGroup = "/platform.service.v1.TenantMenuPermissionGroupService/CreateTenantMenuPermissionGroup"
const OperationTenantMenuPermissionGroupServiceDeleteTenantMenuPermissionGroup = "/platform.service.v1.TenantMenuPermissionGroupService/DeleteTenantMenuPermissionGroup"
const OperationTenantMenuPermissionGroupServiceGetTenantMenuPermissionGroup = "/platform.service.v1.TenantMenuPermissionGroupService/GetTenantMenuPermissionGroup"
const OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroupVersions = "/platform.service.v1.TenantMenuPermissionGroupService/ListTenantMenuPermissionGroupVersions"
const OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroups = "/platform.service.v1.TenantMenuPermissionGroupService/ListTenantMenuPermissionGroups"
const OperationTenantMenuPermissionGroupServicePublishTenantMenuPermissionGroupVersion = "/platform.service.v1.TenantMenuPermissionGroupService/PublishTenantMenuPermissionGroupVersion"
const OperationTenantMenuPermissionGroupServiceRollbackTenantMenuPermissionGroupVersion = "/platform.service.v1.TenantMenuPermissionGroupService/RollbackTenantMenuPermissionGroupVersion"
const OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroup = "/platform.service.v1.TenantMenuPermissionGroupService/UpdateTenantMenuPermissionGroup"
const OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroupStatus = "/platform.service.v1.TenantMenuPermissionGroupService/UpdateTenantMenuPermissionGroupStatus"

type TenantMenuPermissionGroupServiceHTTPServer interface {
	// CreateTenantMenuPermissionGroup 创建菜单权限组
	CreateTenantMenuPermissionGroup(context.Context, *CreateTenantMenuPermissionGroupRequest) (*CreateTenantMenuPermissionGroupResponse, error)
	// DeleteTenantMenuPermissionGroup 删除菜单权限组
	DeleteTenantMenuPermissionGroup(context.Context, *DeleteTenantMenuPermissionGroupRequest) (*DeleteTenantMenuPermissionGroupResponse, error)
	// GetTenantMenuPermissionGroup 获取菜单权限组
	GetTenantMenuPermissionGroup(context.Context, *GetTenantMenuPermissionGroupRequest) (*TenantMenuPermissionGroup, error)
	ListTenantMenuPermissionGroupVersions(context.Context, *ListTenantMenuPermissionGroupVersionsRequest) (*ListTenantMenuPermissionGroupVersionsResponse, error)
	// ListTenantMenuPermissionGroups 获取菜单权限组列表
	ListTenantMenuPermissionGroups(context.Context, *ListTenantMenuPermissionGroupsRequest) (*ListTenantMenuPermissionGroupsResponse, error)
	PublishTenantMenuPermissionGroupVersion(context.Context, *PublishTenantMenuPermissionGroupVersionRequest) (*PublishTenantMenuPermissionGroupVersionResponse, error)
	RollbackTenantMenuPermissionGroupVersion(context.Context, *RollbackTenantMenuPermissionGroupVersionRequest) (*RollbackTenantMenuPermissionGroupVersionResponse, error)
	// UpdateTenantMenuPermissionGroup 更新菜单权限组
	UpdateTenantMenuPermissionGroup(context.Context, *UpdateTenantMenuPermissionGroupRequest) (*UpdateTenantMenuPermissionGroupResponse, error)
	// UpdateTenantMenuPermissionGroupStatus 更新菜单权限组状态
	UpdateTenantMenuPermissionGroupStatus(context.Context, *UpdateTenantMenuPermissionGroupStatusRequest) (*UpdateTenantMenuPermissionGroupStatusResponse, error)
}

func RegisterTenantMenuPermissionGroupServiceHTTPServer(s *http.Server, srv TenantMenuPermissionGroupServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/platform/v1/tenant-menu-permission-groups", _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups0_HTTP_Handler(srv))
	r.GET("/platform/v1/tenant-menu-permission-groups/{id}", _TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup0_HTTP_Handler(srv))
	r.POST("/platform/v1/tenant-menu-permission-groups", _TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup0_HTTP_Handler(srv))
	r.PUT("/platform/v1/tenant-menu-permission-groups/{id}", _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup0_HTTP_Handler(srv))
	r.DELETE("/platform/v1/tenant-menu-permission-groups/{id}", _TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup0_HTTP_Handler(srv))
	r.POST("/platform/v1/tenant-menu-permission-groups/{id}:status-update", _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus0_HTTP_Handler(srv))
	r.GET("/platform/v1/tenant-menu-permission-groups/{group_id}/versions", _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions0_HTTP_Handler(srv))
	r.POST("/platform/v1/tenant-menu-permission-groups/{group_id}/versions:publish", _TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion0_HTTP_Handler(srv))
	r.POST("/platform/v1/tenant-menu-permission-groups/{group_id}/versions:rollback", _TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion0_HTTP_Handler(srv))
}

func _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroups0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTenantMenuPermissionGroupsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroups)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTenantMenuPermissionGroups(ctx, req.(*ListTenantMenuPermissionGroupsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTenantMenuPermissionGroupsResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_GetTenantMenuPermissionGroup0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantMenuPermissionGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceGetTenantMenuPermissionGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenantMenuPermissionGroup(ctx, req.(*GetTenantMenuPermissionGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantMenuPermissionGroup)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_CreateTenantMenuPermissionGroup0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantMenuPermissionGroupRequest
		if err := ctx.Bind(&in.Group); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceCreateTenantMenuPermissionGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenantMenuPermissionGroup(ctx, req.(*CreateTenantMenuPermissionGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTenantMenuPermissionGroupResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroup0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTenantMenuPermissionGroupRequest
		if err := ctx.Bind(&in.Group); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTenantMenuPermissionGroup(ctx, req.(*UpdateTenantMenuPermissionGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTenantMenuPermissionGroupResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_DeleteTenantMenuPermissionGroup0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTenantMenuPermissionGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceDeleteTenantMenuPermissionGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTenantMenuPermissionGroup(ctx, req.(*DeleteTenantMenuPermissionGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTenantMenuPermissionGroupResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_UpdateTenantMenuPermissionGroupStatus0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTenantMenuPermissionGroupStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroupStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTenantMenuPermissionGroupStatus(ctx, req.(*UpdateTenantMenuPermissionGroupStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTenantMenuPermissionGroupStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_ListTenantMenuPermissionGroupVersions0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTenantMenuPermissionGroupVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroupVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTenantMenuPermissionGroupVersions(ctx, req.(*ListTenantMenuPermissionGroupVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTenantMenuPermissionGroupVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_PublishTenantMenuPermissionGroupVersion0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishTenantMenuPermissionGroupVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServicePublishTenantMenuPermissionGroupVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishTenantMenuPermissionGroupVersion(ctx, req.(*PublishTenantMenuPermissionGroupVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishTenantMenuPermissionGroupVersionResponse)
		return ctx.Result(200, reply)
	}
}

func _TenantMenuPermissionGroupService_RollbackTenantMenuPermissionGroupVersion0_HTTP_Handler(srv TenantMenuPermissionGroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RollbackTenantMenuPermissionGroupVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantMenuPermissionGroupServiceRollbackTenantMenuPermissionGroupVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RollbackTenantMenuPermissionGroupVersion(ctx, req.(*RollbackTenantMenuPermissionGroupVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RollbackTenantMenuPermissionGroupVersionResponse)
		return ctx.Result(200, reply)
	}
}

type TenantMenuPermissionGroupServiceHTTPClient interface {
	// CreateTenantMenuPermissionGroup 创建菜单权限组
	CreateTenantMenuPermissionGroup(ctx context.Context, req *CreateTenantMenuPermissionGroupRequest, opts ...http.CallOption) (rsp *CreateTenantMenuPermissionGroupResponse, err error)
	// DeleteTenantMenuPermissionGroup 删除菜单权限组
	DeleteTenantMenuPermissionGroup(ctx context.Context, req *DeleteTenantMenuPermissionGroupRequest, opts ...http.CallOption) (rsp *DeleteTenantMenuPermissionGroupResponse, err error)
	// GetTenantMenuPermissionGroup 获取菜单权限组
	GetTenantMenuPermissionGroup(ctx context.Context, req *GetTenantMenuPermissionGroupRequest, opts ...http.CallOption) (rsp *TenantMenuPermissionGroup, err error)
	ListTenantMenuPermissionGroupVersions(ctx context.Context, req *ListTenantMenuPermissionGroupVersionsRequest, opts ...http.CallOption) (rsp *ListTenantMenuPermissionGroupVersionsResponse, err error)
	// ListTenantMenuPermissionGroups 获取菜单权限组列表
	ListTenantMenuPermissionGroups(ctx context.Context, req *ListTenantMenuPermissionGroupsRequest, opts ...http.CallOption) (rsp *ListTenantMenuPermissionGroupsResponse, err error)
	PublishTenantMenuPermissionGroupVersion(ctx context.Context, req *PublishTenantMenuPermissionGroupVersionRequest, opts ...http.CallOption) (rsp *PublishTenantMenuPermissionGroupVersionResponse, err error)
	RollbackTenantMenuPermissionGroupVersion(ctx context.Context, req *RollbackTenantMenuPermissionGroupVersionRequest, opts ...http.CallOption) (rsp *RollbackTenantMenuPermissionGroupVersionResponse, err error)
	// UpdateTenantMenuPermissionGroup 更新菜单权限组
	UpdateTenantMenuPermissionGroup(ctx context.Context, req *UpdateTenantMenuPermissionGroupRequest, opts ...http.CallOption) (rsp *UpdateTenantMenuPermissionGroupResponse, err error)
	// UpdateTenantMenuPermissionGroupStatus 更新菜单权限组状态
	UpdateTenantMenuPermissionGroupStatus(ctx context.Context, req *UpdateTenantMenuPermissionGroupStatusRequest, opts ...http.CallOption) (rsp *UpdateTenantMenuPermissionGroupStatusResponse, err error)
}

type TenantMenuPermissionGroupServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTenantMenuPermissionGroupServiceHTTPClient(client *http.Client) TenantMenuPermissionGroupServiceHTTPClient {
	return &TenantMenuPermissionGroupServiceHTTPClientImpl{client}
}

// CreateTenantMenuPermissionGroup 创建菜单权限组
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) CreateTenantMenuPermissionGroup(ctx context.Context, in *CreateTenantMenuPermissionGroupRequest, opts ...http.CallOption) (*CreateTenantMenuPermissionGroupResponse, error) {
	var out CreateTenantMenuPermissionGroupResponse
	pattern := "/platform/v1/tenant-menu-permission-groups"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceCreateTenantMenuPermissionGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Group, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTenantMenuPermissionGroup 删除菜单权限组
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) DeleteTenantMenuPermissionGroup(ctx context.Context, in *DeleteTenantMenuPermissionGroupRequest, opts ...http.CallOption) (*DeleteTenantMenuPermissionGroupResponse, error) {
	var out DeleteTenantMenuPermissionGroupResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceDeleteTenantMenuPermissionGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTenantMenuPermissionGroup 获取菜单权限组
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) GetTenantMenuPermissionGroup(ctx context.Context, in *GetTenantMenuPermissionGroupRequest, opts ...http.CallOption) (*TenantMenuPermissionGroup, error) {
	var out TenantMenuPermissionGroup
	pattern := "/platform/v1/tenant-menu-permission-groups/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceGetTenantMenuPermissionGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) ListTenantMenuPermissionGroupVersions(ctx context.Context, in *ListTenantMenuPermissionGroupVersionsRequest, opts ...http.CallOption) (*ListTenantMenuPermissionGroupVersionsResponse, error) {
	var out ListTenantMenuPermissionGroupVersionsResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{group_id}/versions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroupVersions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTenantMenuPermissionGroups 获取菜单权限组列表
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) ListTenantMenuPermissionGroups(ctx context.Context, in *ListTenantMenuPermissionGroupsRequest, opts ...http.CallOption) (*ListTenantMenuPermissionGroupsResponse, error) {
	var out ListTenantMenuPermissionGroupsResponse
	pattern := "/platform/v1/tenant-menu-permission-groups"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceListTenantMenuPermissionGroups))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) PublishTenantMenuPermissionGroupVersion(ctx context.Context, in *PublishTenantMenuPermissionGroupVersionRequest, opts ...http.CallOption) (*PublishTenantMenuPermissionGroupVersionResponse, error) {
	var out PublishTenantMenuPermissionGroupVersionResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{group_id}/versions:publish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServicePublishTenantMenuPermissionGroupVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) RollbackTenantMenuPermissionGroupVersion(ctx context.Context, in *RollbackTenantMenuPermissionGroupVersionRequest, opts ...http.CallOption) (*RollbackTenantMenuPermissionGroupVersionResponse, error) {
	var out RollbackTenantMenuPermissionGroupVersionResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{group_id}/versions:rollback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceRollbackTenantMenuPermissionGroupVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTenantMenuPermissionGroup 更新菜单权限组
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) UpdateTenantMenuPermissionGroup(ctx context.Context, in *UpdateTenantMenuPermissionGroupRequest, opts ...http.CallOption) (*UpdateTenantMenuPermissionGroupResponse, error) {
	var out UpdateTenantMenuPermissionGroupResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Group, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTenantMenuPermissionGroupStatus 更新菜单权限组状态
func (c *TenantMenuPermissionGroupServiceHTTPClientImpl) UpdateTenantMenuPermissionGroupStatus(ctx context.Context, in *UpdateTenantMenuPermissionGroupStatusRequest, opts ...http.CallOption) (*UpdateTenantMenuPermissionGroupStatusResponse, error) {
	var out UpdateTenantMenuPermissionGroupStatusResponse
	pattern := "/platform/v1/tenant-menu-permission-groups/{id}:status-update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantMenuPermissionGroupServiceUpdateTenantMenuPermissionGroupStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
