syntax = "proto3";

package core.service.v1;

import "buf/validate/validate.proto";
import "common/enum/enum.proto";
import "common/pagination/pagination.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

option go_package = "backend-service/api/core/service/v1;v1";

service PostService {
  // 创建岗位
  rpc CreatePost(CreatePostRequest) returns (CreatePostResponse);
  // 更新岗位
  rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse);
  // 删除岗位
  rpc DeletePost(DeletePostRequest) returns (DeletePostResponse);
  // 获取岗位
  rpc GetPost(GetPostRequest) returns (GetPostResponse);
  // 分页查询岗位
  rpc ListPosts(ListPostsRequest) returns (ListPostsResponse);
  // 更新岗位状态
  rpc UpdatePostByStatus(UpdatePostByStatusRequest) returns (UpdatePostByStatusResponse);
}

// 岗位信息
message Post {
  // 岗位ID
  uint32 id = 1;
  // 岗位名称
  optional string name = 2 [
    (buf.validate.field).string = {
      min_len: 1
      max_len: 20
    },
    (gnostic.openapi.v3.property) = {description: "岗位名称"}
  ];
  // 岗位状态 0 未知 1 启用 2 禁用
  optional enum.Status status = 3 [
    (buf.validate.field).enum.defined_only = true,
    (gnostic.openapi.v3.property) = {
      description: "岗位状态"
      default: {number: 1}
    }
  ];
  // 排序字段
  optional int32 sort = 4 [
    (buf.validate.field).int32 = {
      gte: 0
      lte: 100
    },
    (gnostic.openapi.v3.property) = {
      description: "排序字段"
      default: {number: 10}
    }
  ];
  // 岗位描述
  optional string remark = 5 [
    (buf.validate.field).string.max_len = 200,
    (gnostic.openapi.v3.property) = {description: "岗位描述"}
  ];
  // 创建时间
  optional string created_at = 6 [(gnostic.openapi.v3.property) = {description: "创建时间"}];
  // 更新时间
  optional string updated_at = 7 [(gnostic.openapi.v3.property) = {description: "更新时间"}];
}

// 创建岗位请求
message CreatePostRequest {
  Post post = 1 [(buf.validate.field).required = true];
  optional uint32 operator_id = 2 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "操作人ID"}
  ];
}

// 创建岗位响应
message CreatePostResponse {}

// 更新岗位请求
message UpdatePostRequest {
  uint32 id = 1 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "岗位ID"}
  ];
  Post post = 2 [
    (buf.validate.field).required = true,
    (gnostic.openapi.v3.property) = {description: "岗位信息"}
  ];
  optional uint32 operator_id = 3 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "操作人ID"}
  ];
  // Required. Mask of fields to update.
  google.protobuf.FieldMask update_mask = 4 [
    (google.api.field_behavior) = REQUIRED,
    (gnostic.openapi.v3.property) = {description: "更新字段掩码"}
  ];
}

// 更新岗位响应
message UpdatePostResponse {}

// 删除岗位请求
message DeletePostRequest {
  uint32 id = 1 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "岗位ID"}
  ];
  optional uint32 operator_id = 2 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "操作人ID"}
  ];
}

// 删除岗位响应
message DeletePostResponse {}

// 获取岗位请求
message GetPostRequest {
  uint32 id = 1 [
    (buf.validate.field).uint32.gt = 0,
    (gnostic.openapi.v3.property) = {description: "岗位ID"}
  ];
}

// 获取岗位响应
message GetPostResponse {
  Post post = 1;
}

// 分页查询岗位请求
message ListPostsRequest {
  // 当前页码
  string page_token = 1 [
    json_name = "pageToken",
    (gnostic.openapi.v3.property) = {
      description: "当前页码"
      default: {number: 1}
    }
  ];
  // 每页的行数
  int32 page_size = 2 [
    json_name = "pageSize",
    (gnostic.openapi.v3.property) = {
      description: "每一页的行数"
      default: {number: 10}
    }
  ];
  // 是否不分页
  optional bool no_paging = 3 [
    json_name = "nopaging",
    (gnostic.openapi.v3.property) = {description: "是否不分页"}
  ];
  // 岗位名称
  optional string name = 4 [(buf.validate.field).string.max_len = 20];
  // 岗位状态
  optional enum.Status status = 5 [
    (buf.validate.field).enum.defined_only = true,
    (gnostic.openapi.v3.property) = {description: "岗位状态 0 未知 1 启用 2 禁用"}
  ];
  // 岗位描述
  optional string remark = 6 [
    (buf.validate.field).string.max_len = 200,
    (gnostic.openapi.v3.property) = {description: "岗位描述"}
  ];

  // Optional. The standard list filter.
  // Supported fields:
  //    * `name` (i.e. `name="John Doe"`)
  //    * `email` (i.e. `email="admin@go-kratos.dev"`)
  //    * `phone` (i.e. `phone="+1234567890"`)
  //    * `create_time` range (i.e. `timestamp>="2025-01-31T11:30:00-04:00"` where
  //    the timestamp is in RFC 3339 format)
  //
  // More detail in [AIP-160](https://google.aip.dev/160).
  optional string filter = 10 [(gnostic.openapi.v3.property) = {description: "筛选条件"}];
  // Optional. A comma-separated list of fields to order by, sorted in ascending
  // order. Use "desc" after a field name for descending. Supported fields:
  // - `create_time`
  //
  // Example: `create_time desc`.
  optional string order_by = 11 [(gnostic.openapi.v3.property) = {description: "排序字段"}]; // Number of resource to skip in the request.
  // * A request with no page token and a skip value of 30 returns a single
  //   page of results starting with the 31st result.
  // * A request with a page token corresponding to the 51st result (because the
  //   first 50 results were returned on the first page) and a skip value of 30
  //   returns a single page of results starting with the 81st result.
  int32 skip = 12 [(gnostic.openapi.v3.property) = {description: "跳过的行数"}];
}

// 分页查询岗位响应
message ListPostsResponse {
  repeated Post items = 1;
  int32 total = 2;
  string next_page_token = 3;
}

// 更新岗位状态请求
message UpdatePostByStatusRequest {
  uint32 id = 1 [(buf.validate.field).uint32.gt = 0];
  int32 status = 2 [
    (buf.validate.field).int32.gte = 0,
    (buf.validate.field).int32.lte = 1
  ];
}

// 更新岗位状态响应
message UpdatePostByStatusResponse {}
