// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: avmc/admin/v1/i_dept.proto

package v1

import (
	v1 "backend-service/api/core/service/v1"
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDeptServiceCreateDept = "/avmc.admin.v1.DeptService/CreateDept"
const OperationDeptServiceDeleteDept = "/avmc.admin.v1.DeptService/DeleteDept"
const OperationDeptServiceGetDept = "/avmc.admin.v1.DeptService/GetDept"
const OperationDeptServiceListDepts = "/avmc.admin.v1.DeptService/ListDepts"
const OperationDeptServiceListDeptsTree = "/avmc.admin.v1.DeptService/ListDeptsTree"
const OperationDeptServiceUpdateDept = "/avmc.admin.v1.DeptService/UpdateDept"
const OperationDeptServiceUpdateDeptByStatus = "/avmc.admin.v1.DeptService/UpdateDeptByStatus"

type DeptServiceHTTPServer interface {
	// CreateDept 创建部门
	CreateDept(context.Context, *v1.CreateDeptRequest) (*v1.CreateDeptResponse, error)
	// DeleteDept 删除部门
	DeleteDept(context.Context, *v1.DeleteDeptRequest) (*v1.DeleteDeptResponse, error)
	// GetDept 获取部门数据
	GetDept(context.Context, *v1.GetDeptRequest) (*v1.Dept, error)
	// ListDepts 获取部门列表
	ListDepts(context.Context, *v1.ListDeptsRequest) (*v1.ListDeptsResponse, error)
	// ListDeptsTree 获取部门树
	ListDeptsTree(context.Context, *v1.ListDeptsTreeRequest) (*v1.ListDeptsTreeResponse, error)
	// UpdateDept 更新部门
	UpdateDept(context.Context, *v1.UpdateDeptRequest) (*v1.UpdateDeptResponse, error)
	// UpdateDeptByStatus 更新部门状态
	UpdateDeptByStatus(context.Context, *v1.UpdateDeptByStatusRequest) (*v1.UpdateDeptByStatusResponse, error)
}

func RegisterDeptServiceHTTPServer(s *http.Server, srv DeptServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/v1/depts", _DeptService_ListDepts0_HTTP_Handler(srv))
	r.GET("/admin/v1/depts/tree", _DeptService_ListDeptsTree0_HTTP_Handler(srv))
	r.GET("/admin/v1/depts/tree/{parent_id}", _DeptService_ListDeptsTree1_HTTP_Handler(srv))
	r.GET("/admin/v1/depts/{id}", _DeptService_GetDept0_HTTP_Handler(srv))
	r.POST("/admin/v1/depts", _DeptService_CreateDept0_HTTP_Handler(srv))
	r.PUT("/admin/v1/depts/{id}", _DeptService_UpdateDept0_HTTP_Handler(srv))
	r.DELETE("/admin/v1/depts/{id}", _DeptService_DeleteDept0_HTTP_Handler(srv))
	r.PUT("/admin/v1/depts/status-update/{id}", _DeptService_UpdateDeptByStatus0_HTTP_Handler(srv))
}

func _DeptService_ListDepts0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListDeptsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceListDepts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDepts(ctx, req.(*v1.ListDeptsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListDeptsResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_ListDeptsTree0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListDeptsTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceListDeptsTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDeptsTree(ctx, req.(*v1.ListDeptsTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListDeptsTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_ListDeptsTree1_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListDeptsTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceListDeptsTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDeptsTree(ctx, req.(*v1.ListDeptsTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListDeptsTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_GetDept0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.GetDeptRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceGetDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDept(ctx, req.(*v1.GetDeptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.Dept)
		return ctx.Result(200, reply)
	}
}

func _DeptService_CreateDept0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.CreateDeptRequest
		if err := ctx.Bind(&in.Dept); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceCreateDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDept(ctx, req.(*v1.CreateDeptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.CreateDeptResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_UpdateDept0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.UpdateDeptRequest
		if err := ctx.Bind(&in.Dept); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceUpdateDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDept(ctx, req.(*v1.UpdateDeptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.UpdateDeptResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_DeleteDept0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.DeleteDeptRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceDeleteDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDept(ctx, req.(*v1.DeleteDeptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.DeleteDeptResponse)
		return ctx.Result(200, reply)
	}
}

func _DeptService_UpdateDeptByStatus0_HTTP_Handler(srv DeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.UpdateDeptByStatusRequest
		if err := ctx.Bind(&in.Status); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeptServiceUpdateDeptByStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDeptByStatus(ctx, req.(*v1.UpdateDeptByStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.UpdateDeptByStatusResponse)
		return ctx.Result(200, reply)
	}
}

type DeptServiceHTTPClient interface {
	// CreateDept 创建部门
	CreateDept(ctx context.Context, req *v1.CreateDeptRequest, opts ...http.CallOption) (rsp *v1.CreateDeptResponse, err error)
	// DeleteDept 删除部门
	DeleteDept(ctx context.Context, req *v1.DeleteDeptRequest, opts ...http.CallOption) (rsp *v1.DeleteDeptResponse, err error)
	// GetDept 获取部门数据
	GetDept(ctx context.Context, req *v1.GetDeptRequest, opts ...http.CallOption) (rsp *v1.Dept, err error)
	// ListDepts 获取部门列表
	ListDepts(ctx context.Context, req *v1.ListDeptsRequest, opts ...http.CallOption) (rsp *v1.ListDeptsResponse, err error)
	// ListDeptsTree 获取部门树
	ListDeptsTree(ctx context.Context, req *v1.ListDeptsTreeRequest, opts ...http.CallOption) (rsp *v1.ListDeptsTreeResponse, err error)
	// UpdateDept 更新部门
	UpdateDept(ctx context.Context, req *v1.UpdateDeptRequest, opts ...http.CallOption) (rsp *v1.UpdateDeptResponse, err error)
	// UpdateDeptByStatus 更新部门状态
	UpdateDeptByStatus(ctx context.Context, req *v1.UpdateDeptByStatusRequest, opts ...http.CallOption) (rsp *v1.UpdateDeptByStatusResponse, err error)
}

type DeptServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDeptServiceHTTPClient(client *http.Client) DeptServiceHTTPClient {
	return &DeptServiceHTTPClientImpl{client}
}

// CreateDept 创建部门
func (c *DeptServiceHTTPClientImpl) CreateDept(ctx context.Context, in *v1.CreateDeptRequest, opts ...http.CallOption) (*v1.CreateDeptResponse, error) {
	var out v1.CreateDeptResponse
	pattern := "/admin/v1/depts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeptServiceCreateDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Dept, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteDept 删除部门
func (c *DeptServiceHTTPClientImpl) DeleteDept(ctx context.Context, in *v1.DeleteDeptRequest, opts ...http.CallOption) (*v1.DeleteDeptResponse, error) {
	var out v1.DeleteDeptResponse
	pattern := "/admin/v1/depts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeptServiceDeleteDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDept 获取部门数据
func (c *DeptServiceHTTPClientImpl) GetDept(ctx context.Context, in *v1.GetDeptRequest, opts ...http.CallOption) (*v1.Dept, error) {
	var out v1.Dept
	pattern := "/admin/v1/depts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeptServiceGetDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDepts 获取部门列表
func (c *DeptServiceHTTPClientImpl) ListDepts(ctx context.Context, in *v1.ListDeptsRequest, opts ...http.CallOption) (*v1.ListDeptsResponse, error) {
	var out v1.ListDeptsResponse
	pattern := "/admin/v1/depts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeptServiceListDepts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDeptsTree 获取部门树
func (c *DeptServiceHTTPClientImpl) ListDeptsTree(ctx context.Context, in *v1.ListDeptsTreeRequest, opts ...http.CallOption) (*v1.ListDeptsTreeResponse, error) {
	var out v1.ListDeptsTreeResponse
	pattern := "/admin/v1/depts/tree/{parent_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeptServiceListDeptsTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDept 更新部门
func (c *DeptServiceHTTPClientImpl) UpdateDept(ctx context.Context, in *v1.UpdateDeptRequest, opts ...http.CallOption) (*v1.UpdateDeptResponse, error) {
	var out v1.UpdateDeptResponse
	pattern := "/admin/v1/depts/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeptServiceUpdateDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Dept, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDeptByStatus 更新部门状态
func (c *DeptServiceHTTPClientImpl) UpdateDeptByStatus(ctx context.Context, in *v1.UpdateDeptByStatusRequest, opts ...http.CallOption) (*v1.UpdateDeptByStatusResponse, error) {
	var out v1.UpdateDeptByStatusResponse
	pattern := "/admin/v1/depts/status-update/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeptServiceUpdateDeptByStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Status, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
