server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
    enable_swagger: true
    cors:
      headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Authorization"
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      origins:
        - "*"
    middleware:
      auth:
        method: "HS256"
        key: "some_api_key"
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/avmc_system?charset=utf8mb4&parseTime=true&loc=Local
    migrate: true
    debug: true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
